In [1]:
import numpy as np
import pandas as pd
import os

from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import r2_score
from sklearn.experimental import enable_halving_search_cv
from sklearn.model_selection import HalvingGridSearchCV
from sklearn.pipeline import Pipeline

from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso
from sklearn.linear_model import Ridge
from sklearn.preprocessing import PolynomialFeatures
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import ElasticNet

import xgboost as xgb
from lightgbm import LGBMRegressor

## Sunflower

In [2]:
sunflower_dataset = pd.read_csv("./data_1/2022_sunflower_.csv")

In [67]:
sunflower_dataset.head()

,VRYIELDMAS,SECTIONID,Crop,Moisture,Elevation,DRYMATTER,xcoord,ycoord,area,CROPNAME_,...,Fe,Zn,S,P,P_Index,K,K_Index,Na,pH,C.E.C
0,1.305388,-1201171,22,7.7,83.607,92.3,25.837112,48.828905,6.03,Maize,...,68.0,1.7,2.0,8.0,0.8,375.0,3.8,11.0,8.1,23.5
1,1.276285,-1201171,22,7.8,83.485,92.2,25.837130,48.828928,6.03,Maize,...,68.0,1.7,2.0,8.0,0.8,375.0,3.8,11.0,8.1,23.5
2,1.346578,-1201171,22,7.7,83.332,92.3,25.837147,48.828951,6.03,Maize,...,68.0,1.7,2.0,8.0,0.8,375.0,3.8,11.0,8.1,23.5
3,1.632671,-1201171,22,7.7,83.210,92.3,25.837160,48.828970,6.03,Maize,...,68.0,1.7,2.0,8.0,0.8,375.0,3.8,11.0,8.1,23.5
4,1.431187,-1201171,22,7.7,83.119,92.3,25.837173,48.828989,6.03,Maize,...,68.0,1.7,2.0,8.0,0.8,375.0,3.8,11.0,8.1,23.5

In [68]:
sunflower_dataset.columns

Index(['VRYIELDMAS', 'SECTIONID', 'Crop', 'Moisture', 'Elevation', 'DRYMATTER',
       'xcoord', 'ycoord', 'area', 'CROPNAME_', 'Organic M', 'Ca', 'Mg',
       'Mg_Index', 'Mn', 'B', 'Cu', 'Mo', 'Fe', 'Zn', 'S', 'P', 'P_Index', 'K',
       'K_Index', 'Na', 'pH', 'C.E.C'],
      dtype='object')

In [3]:
sunflower_dataset = sunflower_dataset.drop(columns=["CROPNAME_", "Mg_Index", "P_Index", "K_Index"])

In [4]:
sunflower_dataset.isna().sum()

VRYIELDMAS    0
SECTIONID     0
Crop          0
Moisture      0
Elevation     0
DRYMATTER     0
xcoord        0
ycoord        0
area          0
Organic M     0
Ca            0
Mg            0
Mn            0
B             0
Cu            0
Mo            0
Fe            0
Zn            0
S             0
P             0
K             0
Na            0
pH            0
C.E.C         0
dtype: int64

### Regressions

In [5]:
feature_names_0 = ['Moisture', 'Elevation', 'Crop', 
       'xcoord', 'ycoord', 'area', 'Organic M', 'Ca', 'Mg', 'Mn', 'B', 'Cu',
       'Mo', 'Fe', 'Zn', 'S', 'P', 'K', 'Na', 'pH', 'C.E.C']

#### MLR

In [6]:
X_mlr_0 = sunflower_dataset[feature_names_0]
y_mlr_0 = sunflower_dataset["VRYIELDMAS"]

scaler_mlr_0 = StandardScaler()
X_mlr_2 = scaler_mlr_0.fit_transform(X_mlr_0)

X_train_mlr_0, X_test_mlr_0, y_train_mlr_0, y_test_mlr_0 = train_test_split(X_mlr_0, y_mlr_0, test_size=0.2, random_state=0)

In [ ]:
reg_model_0 = LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, positive=False)
reg_model_0 = LinearRegression().fit(X_train_mlr_0, y_train_mlr_0)

In [ ]:
y_pred_mlr_0 = reg_model_0.predict(X_test_mlr_0)  

mae_mlr_0 = metrics.mean_absolute_error(y_test_mlr_0, y_pred_mlr_0)
mse_mlr_0 = metrics.mean_squared_error(y_test_mlr_0, y_pred_mlr_0)
rmse_mlr_0 = np.sqrt(metrics.mean_squared_error(y_test_mlr_0, y_pred_mlr_0))
r_2_mlr_0 = r2_score(y_test_mlr_0, y_pred_mlr_0)

print('Mean Absolute Error:', mae_mlr_0)
print('Mean Square Error:', mse_mlr_0)
print('Root Mean Square Error:', rmse_mlr_0)
print('R^2:', r_2_mlr_0)

Mean Absolute Error: 0.5251430024856615
Mean Square Error: 0.5974504832891356
Root Mean Square Error: 0.7729492113257738
R^2: 0.46659014678086297

#### Lasso

In [11]:
X_lasso_0 = sunflower_dataset[feature_names_0]
y_lasso_0 = sunflower_dataset["VRYIELDMAS"]

scaler_lasso_0 = StandardScaler()
X_lasso_0 = scaler_lasso_0.fit_transform(X_lasso_0)

X_train_lasso_0, X_test_lasso_0, y_train_lasso_0, y_test_lasso_0 = train_test_split(X_lasso_0, y_lasso_0, test_size=0.2, random_state=0)

In [12]:
lasso_model_0 = Lasso(alpha=0.1)
lasso_model_0.fit(X_train_lasso_0, y_train_lasso_0)

Lasso(alpha=0.1)

In [14]:
y_pred_lasso_0 = lasso_model_0.predict(X_test_lasso_0)

mae_lasso_0 = metrics.mean_absolute_error(y_test_lasso_0, y_pred_lasso_0)
mse_lasso_0 = metrics.mean_squared_error(y_test_lasso_0, y_pred_lasso_0)
rmse_lasso_0 = np.sqrt(metrics.mean_squared_error(y_test_lasso_0, y_pred_lasso_0))
r_2_lasso_0 = r2_score(y_test_lasso_0, y_pred_lasso_0)

print('Mean Absolute Error:', mae_lasso_0)
print('Mean Square Error:', mse_lasso_0)
print('Root Mean Square Error:', rmse_lasso_0)
print('R^2:', r_2_lasso_0)

Mean Absolute Error: 0.565219965056653
Mean Square Error: 0.6458520933588082
Root Mean Square Error: 0.8036492352754454
R^2: 0.42337669822743795

#### Ridge

In [15]:
X_ridge_0 = sunflower_dataset[feature_names_0]
y_ridge_0 = sunflower_dataset["VRYIELDMAS"]

scaler_ridge_0 = StandardScaler()
X_ridge_0 = scaler_ridge_0.fit_transform(X_ridge_0)

X_train_ringe_0, X_test_ringe_0, y_train_ringe_0, y_test_ringe_0 = train_test_split(X_ridge_0, y_ridge_0, test_size=0.2, random_state=0)

In [17]:
ridge_model_0 = Ridge(alpha=0.1)
ridge_model_0.fit(X_train_ringe_0, y_train_ringe_0)

Ridge(alpha=0.1)

In [18]:
y_pred_ringe_0 = ridge_model_0.predict(X_test_ringe_0)

mae_ringe_0 = metrics.mean_absolute_error(y_test_ringe_0, y_pred_ringe_0)
mse_ringe_0 = metrics.mean_squared_error(y_test_ringe_0, y_pred_ringe_0)
rmse_ringe_0 = np.sqrt(metrics.mean_squared_error(y_test_ringe_0, y_pred_ringe_0))
r_2_ringe_0 = r2_score(y_test_ringe_0, y_pred_ringe_0)

print('Mean Absolute Error:', mae_ringe_0)
print('Mean Square Error:', mse_ringe_0)
print('Root Mean Square Error:', rmse_ringe_0)
print('R^2:', r_2_ringe_0)

Mean Absolute Error: 0.5251324235605712
Mean Square Error: 0.5974513917942682
Root Mean Square Error: 0.7729497990130201
R^2: 0.466589335658263

#### Polynomial

In [19]:
X_pol_0 = sunflower_dataset[feature_names_0]
y_pol_0 = sunflower_dataset["VRYIELDMAS"]

scaler_pol_0 = StandardScaler()
X_pol_2 = scaler_pol_0.fit_transform(X_pol_0)

X_train_pol_0, X_test_pol_0, y_train_pol_0, y_test_pol_0 = train_test_split(X_pol_0, y_pol_0, test_size=0.2, random_state=0)

In [20]:
lin_pol_0 = LinearRegression()
lin_pol_0.fit(X_train_pol_0, y_train_pol_0)

poly_0 = PolynomialFeatures(degree=2)
X_poly_0 = poly_0.fit_transform(X_train_pol_0)
X_poly_test_0 = poly_0.fit_transform(X_test_pol_0)

poly_0.fit(X_poly_0, y_train_pol_0)
lin2_pol_0 = LinearRegression()
lin2_pol_0.fit(X_poly_0, y_train_pol_0)

LinearRegression()

In [21]:
y_pred_pol_0 = lin2_pol_0.predict(X_poly_test_0)

mae_pol_0 = metrics.mean_absolute_error(y_test_pol_0, y_pred_pol_0)
mse_pol_0 = metrics.mean_squared_error(y_test_pol_0, y_pred_pol_0)
rmse_pol_0 = np.sqrt(metrics.mean_squared_error(y_test_pol_0, y_pred_pol_0))
r_2_pol_0 = r2_score(y_test_pol_0, y_pred_pol_0)

print('Mean Absolute Error:', mae_pol_0)
print('Mean Square Error:', mse_pol_0)
print('Root Mean Square Error:', rmse_pol_0)
print('R^2:', r_2_pol_0)

Mean Absolute Error: 0.49392972897248727
Mean Square Error: 0.5415283706939542
Root Mean Square Error: 0.7358861125839746
R^2: 0.5165179762921563

#### Decision Tree

In [22]:
X_dt_0 = sunflower_dataset[feature_names_0]
y_dt_0 = sunflower_dataset["VRYIELDMAS"]

scaler_dt_0 = StandardScaler()
X_dt_0 = scaler_dt_0.fit_transform(X_dt_0)

X_train_dt_0, X_test_dt_0, y_train_dt_0, y_test_dt_0 = train_test_split(X_dt_0, y_dt_0, test_size=0.2, random_state=0)

In [23]:
regressor_dt_0 = DecisionTreeRegressor(max_depth=10, max_leaf_nodes=64, random_state=42)
regressor_dt_0.fit(X_train_dt_0, y_train_dt_0)

DecisionTreeRegressor(max_depth=10, max_leaf_nodes=64, random_state=42)

In [24]:
y_pred_dt_0 = regressor_dt_0.predict(X_test_dt_0)

mae_dt_0 = metrics.mean_absolute_error(y_test_dt_0, y_pred_dt_0)
mse_dt_0 = metrics.mean_squared_error(y_test_dt_0, y_pred_dt_0)
rmse_dt_0 = np.sqrt(metrics.mean_squared_error(y_test_dt_0, y_pred_dt_0))
r_2_dt_0 = r2_score(y_test_dt_0, y_pred_dt_0)

print('Mean Absolute Error:', mae_dt_0)
print('Mean Square Error:', mse_dt_0)
print('Root Mean Square Error:', rmse_dt_0)
print('R^2:', r_2_dt_0)

Mean Absolute Error: 0.45712191423107673
Mean Square Error: 0.4815034801096458
Root Mean Square Error: 0.693904518006365
R^2: 0.5701088076189689

#### Random Forest

In [25]:
X_rf_0 = sunflower_dataset[feature_names_0]
y_rf_0 = sunflower_dataset["VRYIELDMAS"]

scaler_rf_0 = StandardScaler()
X_rf_0 = scaler_rf_0.fit_transform(X_rf_0)

X_train_rf_0, X_test_rf_0, y_train_rf_0, y_test_rf_0 = train_test_split(X_rf_0, y_rf_0, test_size=0.2, random_state=0)

In [26]:
regr_rf_0 = RandomForestRegressor(max_depth=10, max_leaf_nodes=64, n_estimators=300)
regr_rf_0.fit(X_train_rf_0, y_train_rf_0)

RandomForestRegressor(max_depth=10, max_leaf_nodes=64, n_estimators=300)

In [27]:
y_pred_rf_0 = regr_rf_0.predict(X_test_rf_0)

mae_rf_0 = metrics.mean_absolute_error(y_test_rf_0, y_pred_rf_0)
mse_rf_0 = metrics.mean_squared_error(y_test_rf_0, y_pred_rf_0)
rmse_rf_0 = np.sqrt(metrics.mean_squared_error(y_test_rf_0, y_pred_rf_0))
r_2_rf_0 = r2_score(y_test_rf_0, y_pred_rf_0)

print('Mean Absolute Error:', mae_rf_0)
print('Mean Square Error:', mse_rf_0)
print('Root Mean Square Error:', rmse_rf_0)
print('R^2:', r_2_rf_0)

Mean Absolute Error: 0.44119762916848765
Mean Square Error: 0.44432938559734797
Root Mean Square Error: 0.666580366945613
R^2: 0.6032982163682842

#### KNN

In [28]:
X_knn_0 = sunflower_dataset[feature_names_0]
y_knn_0 = sunflower_dataset["VRYIELDMAS"]

scaler_knn_0 = StandardScaler()
X_knn_0 = scaler_knn_0.fit_transform(X_knn_0)

X_train_knn_0, X_test_knn_0, y_train_knn_0, y_test_knn_0 = train_test_split(X_knn_0, y_knn_0, test_size=0.2, random_state=0)

In [29]:
knn_reg_0 = KNeighborsRegressor(n_neighbors=3)
knn_reg_0.fit(X_train_knn_0, y_train_knn_0)

KNeighborsRegressor(n_neighbors=3)

In [30]:
os.environ['OMP_NUM_THREADS'] = '1'
y_pred_knn_0 = knn_reg_0.predict(X_test_knn_0)

mae_knn_0 = metrics.mean_absolute_error(y_test_knn_0, y_pred_knn_0)
mse_knn_0 = metrics.mean_squared_error(y_test_knn_0, y_pred_knn_0)
rmse_knn_0 = np.sqrt(metrics.mean_squared_error(y_test_knn_0, y_pred_knn_0))
r_2_knn_0 = r2_score(y_test_knn_0, y_pred_knn_0)

print('Mean Absolute Error:', mae_knn_0)
print('Mean Square Error:', mse_knn_0)
print('Root Mean Square Error:', rmse_knn_0)
print('R^2:', r_2_knn_0)

Mean Absolute Error: 0.22060058553741768
Mean Square Error: 0.17351051277775012
Root Mean Square Error: 0.4165459311741625
R^2: 0.8450880537526215

#### Elastcnet

In [31]:
X_en_0 = sunflower_dataset[feature_names_0]
y_en_0 = sunflower_dataset["VRYIELDMAS"]

scaler_en_0 = StandardScaler()
X_en_0 = scaler_en_0.fit_transform(X_en_0)

X_train_en_0, X_test_en_0, y_train_en_0, y_test_en_0 = train_test_split(X_en_0, y_en_0, test_size=0.2, random_state=0)

In [32]:
regr_en_0 = ElasticNet(alpha=1, tol=1e-6)
regr_en_0.fit(X_train_en_0, y_train_en_0)

ElasticNet(alpha=1, tol=1e-06)

In [33]:
y_pred_en_0 = regr_en_0.predict(X_test_en_0)

mae_en_0 = metrics.mean_absolute_error(y_test_en_0, y_pred_en_0)
mse_en_0 = metrics.mean_squared_error(y_test_en_0, y_pred_en_0)
rmse_en_0 = np.sqrt(metrics.mean_squared_error(y_test_en_0, y_pred_en_0))
r_2_en_0 = r2_score(y_test_en_0, y_pred_en_0)

print('Mean Absolute Error:', mae_en_0)
print('Mean Square Error:', mse_en_0)
print('Root Mean Square Error:', rmse_en_0)
print('R^2:', r_2_en_0)

Mean Absolute Error: 0.8370623112245503
Mean Square Error: 1.068489886016451
Root Mean Square Error: 1.033677844406298
R^2: 0.04604138885541054

### Gradient Boosting

#### XGBoost

In [34]:
X_xgb_0 = sunflower_dataset[feature_names_0]
y_xgb_0 = sunflower_dataset["VRYIELDMAS"]

scaler_xgb_0 = StandardScaler()
X_xgb_0 = scaler_xgb_0.fit_transform(X_xgb_0)

X_train_xgb_0, X_test_xgb_0, y_train_xgb_0, y_test_xgb_0 = train_test_split(X_xgb_0, y_xgb_0, test_size=0.2, random_state=0)

In [35]:
regressor_xgb_0 =xgb.XGBRegressor(learning_rate = 0.01,
                           n_estimators  = 700,
                           max_depth     = 10,
                           eval_metric   = 'rmse')

regressor_xgb_0.fit(X_train_xgb_0, y_train_xgb_0)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric='rmse', feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=0.01, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=10, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=700, n_jobs=None,
             num_parallel_tree=None, random_state=None, ...)

In [36]:
y_pred_xgb_0 = regressor_xgb_0.predict(X_test_xgb_0)

mae_xgb_0 = metrics.mean_absolute_error(y_test_xgb_0, y_pred_xgb_0)
mse_xgb_0 = metrics.mean_squared_error(y_test_xgb_0, y_pred_xgb_0)
rmse_xgb_0 = np.sqrt(metrics.mean_squared_error(y_test_xgb_0, y_pred_xgb_0))
r_2_xgb_0 = r2_score(y_test_xgb_0, y_pred_xgb_0)

print('Mean Absolute Error:', mae_xgb_0)
print('Mean Square Error:', mse_xgb_0)
print('Root Mean Square Error:', rmse_xgb_0)
print('R^2:', r_2_xgb_0)

Mean Absolute Error: 0.2909813814857011
Mean Square Error: 0.23478974899916533
Root Mean Square Error: 0.4845510798658541
R^2: 0.7903773299143966

#### LightGBM

In [37]:
X_gbm_0 = sunflower_dataset[feature_names_0]
y_gbm_0 = sunflower_dataset["VRYIELDMAS"]

scaler_gbm_0 = StandardScaler()
X_gbm_0 = scaler_gbm_0.fit_transform(X_gbm_0)

X_train_gbm_0, X_test_gbm_0, y_train_gbm_0, y_test_gbm_0 = train_test_split(X_gbm_0, y_gbm_0, test_size=0.2, random_state=0)

In [38]:
model_gbm_0 = LGBMRegressor(learning_rate=0.1, max_depth=10, n_estimators=100, num_leaves=64)
model_gbm_0.fit(X_train_gbm_0, y_train_gbm_0)

c:\Users\katja\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

LGBMRegressor(max_depth=10, num_leaves=64)

In [39]:
y_pred_gbm_0 = model_gbm_0.predict(X_test_gbm_0)

mae_gbm_0 = metrics.mean_absolute_error(y_test_gbm_0, y_pred_gbm_0)
mse_gbm_0 = metrics.mean_squared_error(y_test_gbm_0, y_pred_gbm_0)
rmse_gbm_0 = np.sqrt(metrics.mean_squared_error(y_test_gbm_0, y_pred_gbm_0))
r_2_gbm_0 = r2_score(y_test_gbm_0, y_pred_gbm_0)

print('Mean Absolute Error:', mae_gbm_0)
print('Mean Square Error:', mse_gbm_0)
print('Root Mean Square Error:', rmse_gbm_0)
print('R^2:', r_2_gbm_0)

Mean Absolute Error: 0.3572045326537401
Mean Square Error: 0.3116560061197385
Root Mean Square Error: 0.5582615929111894
R^2: 0.7217503556713329

c:\Users\katja\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

## All yields with encoded crops

In [40]:
all_yields_df_encoded_crops = pd.read_csv("./data_1/all_yields.csv")

In [41]:
all_yields_df_encoded_crops.head()

,VRYIELDMAS,SECTIONID,Moisture,Elevation,xcoord,ycoord,area,Organic M,Ca,Mg,...,K,Na,pH,C.E.C,year,Crop_22,Crop_34,Crop_41,Crop_45,Crop_174
0,0.000000,499,14.38,269.856182,25.839963,48.834206,5.18,9.5,4901.0,100.0,...,363.0,9.0,8.2,26.9,2018,False,False,False,True,False
1,0.186290,499,14.41,269.818182,25.839974,48.834226,5.18,9.5,4901.0,100.0,...,363.0,9.0,8.2,26.9,2018,False,False,False,True,False
2,0.000000,499,14.44,269.751182,25.839979,48.834244,5.18,9.5,4901.0,100.0,...,363.0,9.0,8.2,26.9,2018,False,False,False,True,False
3,0.143233,499,14.45,269.748182,25.839986,48.834261,5.18,9.5,4901.0,100.0,...,363.0,9.0,8.2,26.9,2018,False,False,False,True,False
4,0.000000,499,14.24,269.713182,25.839996,48.834278,5.18,9.5,4901.0,100.0,...,363.0,9.0,8.2,26.9,2018,False,False,False,True,False

In [42]:
all_yields_df_encoded_crops.columns

Index(['VRYIELDMAS', 'SECTIONID', 'Moisture', 'Elevation', 'xcoord', 'ycoord',
       'area', 'Organic M', 'Ca', 'Mg', 'Mn', 'B', 'Cu', 'Mo', 'Fe', 'Zn', 'S',
       'P', 'K', 'Na', 'pH', 'C.E.C', 'year', 'Crop_22', 'Crop_34', 'Crop_41',
       'Crop_45', 'Crop_174'],
      dtype='object')

In [43]:
feature_names_1 = ['Organic M', 'Ca', 'Mg', 'Mn', 'B',
       'Cu', 'Mo', 'Fe', 'Zn', 'S', 'P', 'K', 'Na', 'pH',
       'C.E.C', 'Crop_22', 'Crop_34', 'Crop_41',
       'Crop_45', 'Crop_174', "year"]

### Regressions

#### MLR

In [44]:
X_mlr_1 = all_yields_df_encoded_crops[feature_names_1]
y_mlr_1 = all_yields_df_encoded_crops["VRYIELDMAS"]

scaler_mlr_1 = StandardScaler()
X_mlr_1 = scaler_mlr_1.fit_transform(X_mlr_1)

X_train_mlr_1, X_test_mlr_1, y_train_mlr_1, y_test_mlr_1 = train_test_split(X_mlr_1, y_mlr_1, test_size=0.2, random_state=0)

In [45]:
reg_model_mlr_1 = LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, positive=False)
reg_model_mlr_1 = LinearRegression().fit(X_train_mlr_1, y_train_mlr_1)

In [47]:
y_pred_mlr_1 = reg_model_mlr_1.predict(X_test_mlr_1)  

mae_mlr_1 = metrics.mean_absolute_error(y_test_mlr_1, y_pred_mlr_1)
mse_mlr_1 = metrics.mean_squared_error(y_test_mlr_1, y_pred_mlr_1)
rmse_mlr_1 = np.sqrt(metrics.mean_squared_error(y_test_mlr_1, y_pred_mlr_1))
r_2_mlr_1 = r2_score(y_test_mlr_1, y_pred_mlr_1)

print('Mean Absolute Error:', mae_mlr_1)
print('Mean Square Error:', mse_mlr_1)
print('Root Mean Square Error:', rmse_mlr_1)
print('R^2:', r_2_mlr_1)

Mean Absolute Error: 0.8821012264383473
Mean Square Error: 1.6089170107804218
Root Mean Square Error: 1.2684309247177876
R^2: 0.9447669919790752

#### Lasso

In [48]:
X_lasso_1 = all_yields_df_encoded_crops[feature_names_1]
y_lasso_1 = all_yields_df_encoded_crops["VRYIELDMAS"]

scaler_lasso_1 = StandardScaler()
X_lasso_1 = scaler_lasso_1.fit_transform(X_lasso_1)

X_train_lasso_1, X_test_lasso_1, y_train_lasso_1, y_test_lasso_1 = train_test_split(X_lasso_1, y_lasso_1, test_size=0.2, random_state=0)

In [49]:
lasso_model_1 = Lasso(alpha=0.1)
lasso_model_1.fit(X_train_lasso_1, y_train_lasso_1)

Lasso(alpha=0.1)

In [50]:
y_pred_lasso_1 = lasso_model_1.predict(X_test_lasso_1)

mae_lasso_1 = metrics.mean_absolute_error(y_test_lasso_1, y_pred_lasso_1)
mse_lasso_1 = metrics.mean_squared_error(y_test_lasso_1, y_pred_lasso_1)
rmse_lasso_1 = np.sqrt(metrics.mean_squared_error(y_test_lasso_1, y_pred_lasso_1))
r_2_lasso_1 = r2_score(y_test_lasso_1, y_pred_lasso_1)

print('Mean Absolute Error:', mae_lasso_1)
print('Mean Square Error:', mse_lasso_1)
print('Root Mean Square Error:', rmse_lasso_1)
print('R^2:', r_2_lasso_1)

Mean Absolute Error: 1.0217623750983624
Mean Square Error: 2.064282586052848
Root Mean Square Error: 1.436761144398347
R^2: 0.9291346067765127

#### Ridge

In [51]:
X_ridge_1 = all_yields_df_encoded_crops[feature_names_1]
y_ridge_1 = all_yields_df_encoded_crops["VRYIELDMAS"]

scaler_ridge_1 = StandardScaler()
X_ridge_1 = scaler_ridge_1.fit_transform(X_ridge_1)

X_train_ridge_1, X_test_ridge_1, y_train_ridge_1, y_test_ridge_1 = train_test_split(X_ridge_1, y_ridge_1, test_size=0.2, random_state=0)

In [52]:
ridge_model_1 = Ridge(alpha=0.1)
ridge_model_1.fit(X_train_ridge_1, y_train_ridge_1)

Ridge(alpha=0.1)

In [53]:
y_pred_ridge_1 = ridge_model_1.predict(X_test_ridge_1)

mae_ridge_1 = metrics.mean_absolute_error(y_test_ridge_1, y_pred_ridge_1)
mse_ridge_1 = metrics.mean_squared_error(y_test_ridge_1, y_pred_ridge_1)
rmse_ridge_1 = np.sqrt(metrics.mean_squared_error(y_test_ridge_1, y_pred_ridge_1))
r_2_ridge_1 = r2_score(y_test_ridge_1, y_pred_ridge_1)

print('Mean Absolute Error:', mae_ridge_1)
print('Mean Square Error:', mse_ridge_1)
print('Root Mean Square Error:', rmse_ridge_1)
print('R^2:', r_2_ridge_1)

Mean Absolute Error: 0.8821004548369846
Mean Square Error: 1.6089161857138248
Root Mean Square Error: 1.2684305994865563
R^2: 0.9447670203030407

#### Polynomial

In [54]:
X_pol_1 = all_yields_df_encoded_crops[feature_names_1]
y_pol_1 = all_yields_df_encoded_crops["VRYIELDMAS"]

scaler_pol_1 = StandardScaler()
X_pol_1 = scaler_pol_1.fit_transform(X_pol_1)

X_train_pol_1, X_test_pol_1, y_train_pol_1, y_test_pol_1 = train_test_split(X_pol_1, y_pol_1, test_size=0.2, random_state=0)

In [55]:
lin_1 = LinearRegression()
lin_1.fit(X_train_pol_1, y_train_pol_1)

poly_1 = PolynomialFeatures(degree=2)
X_poly_1 = poly_1.fit_transform(X_train_pol_1)
X_poly_test_1 = poly_1.fit_transform(X_test_pol_1)

poly_1.fit(X_poly_1, y_train_pol_1)
lin2_1 = LinearRegression()
lin2_1.fit(X_poly_1, y_train_pol_1)

LinearRegression()

In [56]:
y_pred_pol_1 = lin2_1.predict(X_poly_test_1)

mae_pol_1 = metrics.mean_absolute_error(y_test_pol_1, y_pred_pol_1)
mse_pol_1 = metrics.mean_squared_error(y_test_pol_1, y_pred_pol_1)
rmse_pol_1 = np.sqrt(metrics.mean_squared_error(y_test_pol_1, y_pred_pol_1))
r_2_pol_1 = r2_score(y_test_pol_1, y_pred_pol_1)

print('Mean Absolute Error:', mae_pol_1)
print('Mean Square Error:', mse_pol_1)
print('Root Mean Square Error:', rmse_pol_1)
print('R^2:', r_2_pol_1)

Mean Absolute Error: 0.8219413235027695
Mean Square Error: 1.4616389977923638
Root Mean Square Error: 1.2089826292351615
R^2: 0.9498229442862296

#### Decision Tree

In [57]:
X_dt_1 = all_yields_df_encoded_crops[feature_names_1]
y_dt_1 = all_yields_df_encoded_crops["VRYIELDMAS"]

scaler_dt_1 = StandardScaler()
X_dt_1 = scaler_dt_1.fit_transform(X_dt_1)

X_train_dt_1, X_test_dt_1, y_train_dt_1, y_test_dt_1 = train_test_split(X_dt_1, y_dt_1, test_size=0.2, random_state=0)

In [58]:
regressor_dt_1 = DecisionTreeRegressor(max_depth=10, max_leaf_nodes=64, random_state=42)
regressor_dt_1.fit(X_train_dt_1, y_train_dt_1)

DecisionTreeRegressor(max_depth=10, max_leaf_nodes=64, random_state=42)

In [59]:
y_pred_dt_1 = regressor_dt_1.predict(X_test_dt_1)

mae_dt_1 = metrics.mean_absolute_error(y_test_dt_1, y_pred_dt_1)
mse_dt_1 = metrics.mean_squared_error(y_test_dt_1, y_pred_dt_1)
rmse_dt_1 = np.sqrt(metrics.mean_squared_error(y_test_dt_1, y_pred_dt_1))
r_2_dt_1 = r2_score(y_test_dt_1, y_pred_dt_1)

print('Mean Absolute Error:', mae_dt_1)
print('Mean Square Error:', mse_dt_1)
print('Root Mean Square Error:', rmse_dt_1)
print('R^2:', r_2_dt_1)

Mean Absolute Error: 0.8221007171917343
Mean Square Error: 1.461420989377515
Root Mean Square Error: 1.2088924639427259
R^2: 0.9498304283643053

#### Random Forest

In [60]:
X_rf_1 = all_yields_df_encoded_crops[feature_names_1]
y_rf_1 = all_yields_df_encoded_crops["VRYIELDMAS"]

scaler_rf_1 = StandardScaler()
X_rf_1 = scaler_rf_1.fit_transform(X_rf_1)

X_train_rf_1, X_test_rf_1, y_train_rf_1, y_test_rf_1 = train_test_split(X_rf_1, y_rf_1, test_size=0.2, random_state=0)

In [61]:
regr_rf_1 = RandomForestRegressor(max_depth=10, max_leaf_nodes=64, n_estimators=300)
regr_rf_1.fit(X_train_rf_1, y_train_rf_1)

RandomForestRegressor(max_depth=10, max_leaf_nodes=64, n_estimators=300)

In [62]:
y_pred_rf_1 = regr_rf_1.predict(X_test_rf_1)

mae_rf_1 = metrics.mean_absolute_error(y_test_rf_1, y_pred_rf_1)
mse_rf_1 = metrics.mean_squared_error(y_test_rf_1, y_pred_rf_1)
rmse_rf_1 = np.sqrt(metrics.mean_squared_error(y_test_rf_1, y_pred_rf_1))
r_2_rf_1 = r2_score(y_test_rf_1, y_pred_rf_1)

print('Mean Absolute Error:', mae_rf_1)
print('Mean Square Error:', mse_rf_1)
print('Root Mean Square Error:', rmse_rf_1)
print('R^2:', r_2_rf_1)

Mean Absolute Error: 0.8219803827401629
Mean Square Error: 1.4615503822936613
Root Mean Square Error: 1.2089459798906075
R^2: 0.9498259863950008

#### KNN

In [63]:
X_knn_1 = all_yields_df_encoded_crops[feature_names_1]
y_knn_1 = all_yields_df_encoded_crops["VRYIELDMAS"]

scaler_knn_1 = StandardScaler()
X_knn_1 = scaler_knn_1.fit_transform(X_knn_1)

X_train_knn_1, X_test_knn_1, y_train_knn_1, y_test_knn_1 = train_test_split(X_knn_1, y_knn_1, test_size=0.2, random_state=0)

In [64]:
knn_reg_1 = KNeighborsRegressor(n_neighbors=3)
knn_reg_1.fit(X_train_knn_1, y_train_knn_1)

KNeighborsRegressor(n_neighbors=3)

In [65]:
os.environ['OMP_NUM_THREADS'] = '1'
y_pred_knn_1 = knn_reg_1.predict(X_test_knn_1)

mae_knn_1 = metrics.mean_absolute_error(y_test_knn_1, y_pred_knn_1)
mse_knn_1 = metrics.mean_squared_error(y_test_knn_1, y_pred_knn_1)
rmse_knn_1 = np.sqrt(metrics.mean_squared_error(y_test_knn_1, y_pred_knn_1))
r_2_knn_1 = r2_score(y_test_knn_1, y_pred_knn_1)

print('Mean Absolute Error:', mae_knn_1)
print('Mean Square Error:', mse_knn_1)
print('Root Mean Square Error:', rmse_knn_1)
print('R^2:', r_2_knn_1)

Mean Absolute Error: 0.9050483909241005
Mean Square Error: 1.7179985105820395
Root Mean Square Error: 1.3107244220590533
R^2: 0.9410222995473911

#### Elastcnet

In [66]:
X_en_1 = all_yields_df_encoded_crops[feature_names_1]
y_en_1 = all_yields_df_encoded_crops["VRYIELDMAS"]

scaler_en_1 = StandardScaler()
X_en_1 = scaler_en_1.fit_transform(X_en_1)

X_train_en_1, X_test_en_1, y_train_en_1, y_test_en_1 = train_test_split(X_en_1, y_en_1, test_size=0.2, random_state=0)

In [67]:
regr_en_1 = ElasticNet(alpha=1, tol=1e-6)
regr_en_1.fit(X_train_en_1, y_train_en_1)

ElasticNet(alpha=1, tol=1e-06)

In [68]:
y_pred_en_1 = regr_en_1.predict(X_test_en_1)

mae_en_1 = metrics.mean_absolute_error(y_test_en_1, y_pred_en_1)
mse_en_1 = metrics.mean_squared_error(y_test_en_1, y_pred_en_1)
rmse_en_1 = np.sqrt(metrics.mean_squared_error(y_test_en_1, y_pred_en_1))
r_2_en_1 = r2_score(y_test_en_1, y_pred_en_1)

print('Mean Absolute Error:', mae_en_1)
print('Mean Square Error:', mse_en_1)
print('Root Mean Square Error:', rmse_en_1)
print('R^2:', r_2_en_1)

Mean Absolute Error: 2.1690925043960436
Mean Square Error: 6.92298532589812
Root Mean Square Error: 2.631156651721467
R^2: 0.7623387026975372

### Gradient Boosting

#### XGBoost

In [69]:
X_xgb_1 = all_yields_df_encoded_crops[feature_names_1]
y_xgb_1 = all_yields_df_encoded_crops["VRYIELDMAS"]

scaler_xgb_1 = StandardScaler()
X_xgb_1 = scaler_xgb_1.fit_transform(X_xgb_1)

X_train_xgb_1, X_test_xgb_1, y_train_xgb_1, y_test_xgb_1 = train_test_split(X_xgb_1, y_xgb_1, test_size=0.2, random_state=0)

In [70]:
regressor_1 = xgb.XGBRegressor(learning_rate = 0.01,
                           n_estimators  = 700,
                           max_depth     = 10,
                           eval_metric   = 'rmse')

regressor_1.fit(X_train_xgb_1, y_train_xgb_1)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric='rmse', feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=0.01, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=10, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=700, n_jobs=None,
             num_parallel_tree=None, random_state=None, ...)

In [71]:
y_pred_xgb_1 = regressor_1.predict(X_test_xgb_1)

mae_xgb_1 = metrics.mean_absolute_error(y_test_xgb_1, y_pred_xgb_1)
mse_xgb_1 = metrics.mean_squared_error(y_test_xgb_1, y_pred_xgb_1)
rmse_xgb_1 = np.sqrt(metrics.mean_squared_error(y_test_xgb_1, y_pred_xgb_1))
r_2_xgb_1 = r2_score(y_test_xgb_1, y_pred_xgb_1)

print('Mean Absolute Error:', mae_xgb_1)
print('Mean Square Error:', mse_xgb_1)
print('Root Mean Square Error:', rmse_xgb_1)
print('R^2:', r_2_xgb_1)

Mean Absolute Error: 0.8217676167463202
Mean Square Error: 1.461507151729758
Root Mean Square Error: 1.2089281003143892
R^2: 0.9498274704703551

#### LightGBM

In [72]:
X_gbm_1 = all_yields_df_encoded_crops[feature_names_1]
y_gbm_1 = all_yields_df_encoded_crops["VRYIELDMAS"]

scaler_gbm_1 = StandardScaler()
X_gbm_1 = scaler_gbm_1.fit_transform(X_gbm_1)

X_train_gbm_1, X_test_gbm_1, y_train_gbm_1, y_test_gbm_1 = train_test_split(X_gbm_1, y_gbm_1, test_size=0.2, random_state=0)

In [73]:
model_gbm_1 = LGBMRegressor(learning_rate=0.1, max_depth=10, n_estimators=100, num_leaves=64)
model_gbm_1.fit(X_train_gbm_1, y_train_gbm_1)

c:\Users\katja\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

LGBMRegressor(max_depth=10, num_leaves=64)

In [74]:
y_pred_gbm_1 = model_gbm_1.predict(X_test_gbm_1)

mae_gbm_1 = metrics.mean_absolute_error(y_test_gbm_1, y_pred_gbm_1)
mse_gbm_1 = metrics.mean_squared_error(y_test_gbm_1, y_pred_gbm_1)
rmse_gbm_1 = np.sqrt(metrics.mean_squared_error(y_test_gbm_1, y_pred_gbm_1))
r_2_gbm_1 = r2_score(y_test_gbm_1, y_pred_gbm_1)

print('Mean Absolute Error:', mae_gbm_1)
print('Mean Square Error:', mse_gbm_1)
print('Root Mean Square Error:', rmse_gbm_1)
print('R^2:', r_2_gbm_1)

Mean Absolute Error: 0.8218584900394428
Mean Square Error: 1.4614772236247917
Root Mean Square Error: 1.2089157223002733
R^2: 0.949828497881496

c:\Users\katja\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

## Without encoded crops

In [75]:
all_yields_df_encoded_crops.head()

,VRYIELDMAS,SECTIONID,Moisture,Elevation,xcoord,ycoord,area,Organic M,Ca,Mg,...,K,Na,pH,C.E.C,year,Crop_22,Crop_34,Crop_41,Crop_45,Crop_174
0,0.000000,499,14.38,269.856182,25.839963,48.834206,5.18,9.5,4901.0,100.0,...,363.0,9.0,8.2,26.9,2018,False,False,False,True,False
1,0.186290,499,14.41,269.818182,25.839974,48.834226,5.18,9.5,4901.0,100.0,...,363.0,9.0,8.2,26.9,2018,False,False,False,True,False
2,0.000000,499,14.44,269.751182,25.839979,48.834244,5.18,9.5,4901.0,100.0,...,363.0,9.0,8.2,26.9,2018,False,False,False,True,False
3,0.143233,499,14.45,269.748182,25.839986,48.834261,5.18,9.5,4901.0,100.0,...,363.0,9.0,8.2,26.9,2018,False,False,False,True,False
4,0.000000,499,14.24,269.713182,25.839996,48.834278,5.18,9.5,4901.0,100.0,...,363.0,9.0,8.2,26.9,2018,False,False,False,True,False

In [76]:
feature_names = ['Moisture', 'Elevation', 'xcoord', 'ycoord',
       'area', 'Organic M', 'Ca', 'Mg', 'Mn', 'B',
       'Cu', 'Mo', 'Fe', 'Zn', 'S', 'P', 'K', 'Na', 'pH',
       'C.E.C']

### Regressions

#### Multiple Linear Regression

In [77]:
X_mlr_ = all_yields_df_encoded_crops[feature_names]
y_mlr_ = all_yields_df_encoded_crops["VRYIELDMAS"]

scaler_mlr_ = StandardScaler()
X_mlr_ = scaler_mlr_.fit_transform(X_mlr_)

X_train_mlr_, X_test_mlr_, y_train_mlr_, y_test_mlr_ = train_test_split(X_mlr_, y_mlr_, test_size=0.2, random_state=0)

In [78]:
reg_model = LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, positive=False)
reg_model = LinearRegression().fit(X_train_mlr_, y_train_mlr_)

In [79]:
y_pred= reg_model.predict(X_test_mlr_)  

mae = metrics.mean_absolute_error(y_test_mlr_, y_pred)
mse = metrics.mean_squared_error(y_test_mlr_, y_pred)
r2 = np.sqrt(metrics.mean_squared_error(y_test_mlr_, y_pred))
r_2 = r2_score(y_test_mlr_, y_pred)

print('Mean Absolute Error:', mae)
print('Mean Square Error:', mse)
print('Root Mean Square Error:', r2)
print('R^2:', r_2)

Mean Absolute Error: 2.7712884023751863
Mean Square Error: 11.120167170183892
Root Mean Square Error: 3.334691465515797
R^2: 0.6182523533598123

#### Lasso

In [80]:
X_lasso = all_yields_df_encoded_crops[feature_names]
y_lasso = all_yields_df_encoded_crops["VRYIELDMAS"]

scaler_lasso = StandardScaler()
X_lasso_ = scaler_lasso.fit_transform(X_lasso)

X_train_lasso, X_test_lasso, y_train_lasso, y_test_lasso = train_test_split(X_lasso, y_lasso, test_size=0.2, random_state=0)

In [81]:
lasso_model = Lasso(alpha=0.1)
lasso_model.fit(X_train_lasso, y_train_lasso)

Lasso(alpha=0.1)

In [82]:
y_pred_lasso = lasso_model.predict(X_test_lasso)

mae_lasso = metrics.mean_absolute_error(y_test_lasso, y_pred_lasso)
mse_lasso = metrics.mean_squared_error(y_test_lasso, y_pred_lasso)
rmse_lasso = np.sqrt(metrics.mean_squared_error(y_test_lasso, y_pred_lasso))
r_2_lasso = r2_score(y_test_lasso, y_pred_lasso)

print('Mean Absolute Error:', mae_lasso)
print('Mean Square Error:', mse_lasso)
print('Root Mean Square Error:', rmse_lasso)
print('R^2:', r_2_lasso)

Mean Absolute Error: 2.7879837447723483
Mean Square Error: 11.291100934022133
Root Mean Square Error: 3.3602233458539823
R^2: 0.6123843154897017

#### Ridge

In [83]:
X_ridge = all_yields_df_encoded_crops[feature_names]
y_ridge = all_yields_df_encoded_crops["VRYIELDMAS"]

scaler_ridge = StandardScaler()
X_ridge_2 = scaler_ridge.fit_transform(X_ridge)

X_train_ridge, X_test_ridge, y_train_ridge, y_test_ridge = train_test_split(X_ridge, y_ridge, test_size=0.2, random_state=0)

In [84]:
ridge_model = Ridge(alpha=0.1)
ridge_model.fit(X_train_ridge, y_train_ridge)

Ridge(alpha=0.1)

In [85]:
y_pred_ridge = ridge_model.predict(X_test_ridge)

mae_ridge = metrics.mean_absolute_error(y_test_ridge, y_pred_ridge)
mse_ridge = metrics.mean_squared_error(y_test_ridge, y_pred_ridge)
rmse_ridge = np.sqrt(metrics.mean_squared_error(y_test_ridge, y_pred_ridge))
r_2_ridge = r2_score(y_test_ridge, y_pred_ridge)

print('Mean Absolute Error:', mae_ridge)
print('Mean Square Error:', mse_ridge)
print('Root Mean Square Error:', rmse_ridge)
print('R^2:', r_2_ridge)

Mean Absolute Error: 2.770275910104312
Mean Square Error: 11.12167726470435
Root Mean Square Error: 3.334917879754215
R^2: 0.6182005128595243

#### Polynomial

In [86]:
X_pol = all_yields_df_encoded_crops[feature_names]
y_pol = all_yields_df_encoded_crops["VRYIELDMAS"]

scaler_pol = StandardScaler()
X_pol = scaler_pol.fit_transform(X_pol)

X_train_pol, X_test_pol, y_train_pol, y_test_pol = train_test_split(X_pol, y_pol, test_size=0.2, random_state=0)

In [87]:
lin_ = LinearRegression()
lin_.fit(X_train_pol, y_train_pol)

poly_ = PolynomialFeatures(degree=2)
X_poly_ = poly_.fit_transform(X_train_pol)
X_poly_test_ = poly_.fit_transform(X_test_pol)

poly_.fit(X_poly_, y_train_pol)
lin2_ = LinearRegression()
lin2_.fit(X_poly_, y_train_pol)

LinearRegression()

In [88]:
y_pred_pol = lin2_.predict(X_poly_test_)

mae_pol = metrics.mean_absolute_error(y_test_pol, y_pred_pol)
mse_pol = metrics.mean_squared_error(y_test_pol, y_pred_pol)
rmse_pol = np.sqrt(metrics.mean_squared_error(y_test_pol, y_pred_pol))
r_2_pol = r2_score(y_test_pol, y_pred_pol)

print('Mean Absolute Error:', mae_pol)
print('Mean Square Error:', mse_pol)
print('Root Mean Square Error:', rmse_pol)
print('R^2:', r_2_pol)

Mean Absolute Error: 2.6273539937892645
Mean Square Error: 10.138812724370458
Root Mean Square Error: 3.1841502358353724
R^2: 0.6519415726382459

#### Decision Tree

In [89]:
X_dt = all_yields_df_encoded_crops[feature_names]
y_dt = all_yields_df_encoded_crops["VRYIELDMAS"]

scaler_dt = StandardScaler()
X_dt = scaler_dt.fit_transform(X_dt)

X_train_dt, X_test_dt, y_train_dt, y_test_dt = train_test_split(X_dt, y_dt, test_size=0.2, random_state=0)

In [90]:
regressor_dt = DecisionTreeRegressor(max_depth=10, max_leaf_nodes=64, random_state=42)
regressor_dt.fit(X_train_dt, y_train_dt)

DecisionTreeRegressor(max_depth=10, max_leaf_nodes=64, random_state=42)

In [91]:
y_pred_dt = regressor_dt.predict(X_test_dt)

mae_dt = metrics.mean_absolute_error(y_test_dt, y_pred_dt)
mse_dt = metrics.mean_squared_error(y_test_dt, y_pred_dt)
rmse_dt = np.sqrt(metrics.mean_squared_error(y_test_dt, y_pred_dt))
r_2_dt = r2_score(y_test_dt, y_pred_dt)

print('Mean Absolute Error:', mae_dt)
print('Mean Square Error:', mse_dt)
print('Root Mean Square Error:', rmse_dt)
print('R^2:', r_2_dt)

Mean Absolute Error: 0.8214173388918679
Mean Square Error: 1.502954650255576
Root Mean Square Error: 1.2259505088932325
R^2: 0.9484046065170345

#### Random Forest

In [92]:
X_rf = all_yields_df_encoded_crops[feature_names]
y_rf = all_yields_df_encoded_crops["VRYIELDMAS"]

scaler_rf = StandardScaler()
X_rf = scaler_rf.fit_transform(X_rf)

X_train_rf, X_test_rf, y_train_rf, y_test_rf = train_test_split(X_rf, y_rf, test_size=0.2, random_state=0)

In [93]:
regr_rf = RandomForestRegressor(max_depth=10, max_leaf_nodes=64, n_estimators=300)
regr_rf.fit(X_train_rf, y_train_rf)

RandomForestRegressor(max_depth=10, max_leaf_nodes=64, n_estimators=300)

In [94]:
y_pred_rf = regr_rf.predict(X_test_rf)

mae_rf = metrics.mean_absolute_error(y_test_rf, y_pred_rf)
mse_rf = metrics.mean_squared_error(y_test_rf, y_pred_rf)
rmse_rf = np.sqrt(metrics.mean_squared_error(y_test_rf, y_pred_rf))
r_2_rf = r2_score(y_test_rf, y_pred_rf)

print('Mean Absolute Error:', mae_rf)
print('Mean Square Error:', mse_rf)
print('Root Mean Square Error:', rmse_rf)
print('R^2:', r_2_rf)

Mean Absolute Error: 0.7989370446375506
Mean Square Error: 1.4137011856800203
Root Mean Square Error: 1.1889916676243026
R^2: 0.9514686162153382

#### KNN

In [95]:
X_knn = all_yields_df_encoded_crops[feature_names]
y_knn = all_yields_df_encoded_crops["VRYIELDMAS"]

scaler_knn = StandardScaler()
X_knn = scaler_knn.fit_transform(X_knn)

X_train_knn, X_test_knn, y_train_knn, y_test_knn = train_test_split(X_knn, y_knn, test_size=0.2, random_state=0)

In [96]:
knn_reg = KNeighborsRegressor(n_neighbors=3)
knn_reg.fit(X_train_knn, y_train_knn)

KNeighborsRegressor(n_neighbors=3)

In [97]:
os.environ['OMP_NUM_THREADS'] = '1'
y_pred_knn = knn_reg.predict(X_test_knn)

mae_knn = metrics.mean_absolute_error(y_test_knn, y_pred_knn)
mse_knn = metrics.mean_squared_error(y_test_knn, y_pred_knn)
rmse_knn = np.sqrt(metrics.mean_squared_error(y_test_knn, y_pred_knn))
r_2_knn = r2_score(y_test_knn, y_pred_knn)

print('Mean Absolute Error:', mae_knn)
print('Mean Square Error:', mse_knn)
print('Root Mean Square Error:', rmse_knn)
print('R^2:', r_2_knn)

Mean Absolute Error: 0.3872287398909805
Mean Square Error: 0.5618309452302568
Root Mean Square Error: 0.74955383077552
R^2: 0.9807127322935977

#### Elastcnet

In [98]:
X_en = all_yields_df_encoded_crops[feature_names]
y_en = all_yields_df_encoded_crops["VRYIELDMAS"]

scaler_en = StandardScaler()
X_en = scaler_en.fit_transform(X_en)

X_train_en, X_test_en, y_train_en, y_test_en = train_test_split(X_en, y_en, test_size=0.2, random_state=0)

In [99]:
regr_en = ElasticNet(alpha=1, tol=1e-6)
regr_en.fit(X_train_en, y_train_en)

ElasticNet(alpha=1, tol=1e-06)

In [101]:
y_pred_en = regr_en.predict(X_test_en)

mae_en = metrics.mean_absolute_error(y_test_en, y_pred_en)
mse_en = metrics.mean_squared_error(y_test_en, y_pred_en)
rmse_en = np.sqrt(metrics.mean_squared_error(y_test_en, y_pred_en))
r_2_en = r2_score(y_test_en, y_pred_en)

print('Mean Absolute Error:', mae_en)
print('Mean Square Error:', mse_en)
print('Root Mean Square Error:', rmse_en)
print('R^2:', r_2_en)

Mean Absolute Error: 3.1997141315151083
Mean Square Error: 14.76709402751527
Root Mean Square Error: 3.8427976823553007
R^2: 0.4930558770884824

### Gradient Boosting

#### XGBoost

In [102]:
X_xgb = all_yields_df_encoded_crops[feature_names]
y_xgb = all_yields_df_encoded_crops["VRYIELDMAS"]

scaler_xgb = StandardScaler()
X_xgb = scaler_xgb.fit_transform(X_xgb)

X_train_xgb, X_test_xgb, y_train_xgb, y_test_xgb = train_test_split(X_xgb, y_xgb, test_size=0.2, random_state=0)

In [103]:
regressor = xgb.XGBRegressor(learning_rate = 0.01,
                           n_estimators  = 700,
                           max_depth     = 10,
                           eval_metric   = 'rmse')

regressor.fit(X_train_xgb, y_train_xgb)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric='rmse', feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=0.01, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=10, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=700, n_jobs=None,
             num_parallel_tree=None, random_state=None, ...)

In [104]:
y_pred_xgb = regressor.predict(X_test_xgb)

mae_xgb = metrics.mean_absolute_error(y_test_xgb, y_pred_xgb)
mse_xgb = metrics.mean_squared_error(y_test_xgb, y_pred_xgb)
rmse_xgb = np.sqrt(metrics.mean_squared_error(y_test_xgb, y_pred_xgb))
r_2_xgb = r2_score(y_test_xgb, y_pred_xgb)

print('Mean Absolute Error:', mae_xgb)
print('Mean Square Error:', mse_xgb)
print('Root Mean Square Error:', rmse_xgb)
print('R^2:', r_2_xgb)

Mean Absolute Error: 0.5571069767208577
Mean Square Error: 0.7634179209967967
Root Mean Square Error: 0.8737379017742086
R^2: 0.9737923908621733

In [41]:
import joblib 

filename = './models/xgb_2.sav'
scaler_filename = "./models/scaler_xgb_2.pkl"
joblib.dump(regressor, filename)
joblib.dump(scaler_xgb, scaler_filename)

['./models/scaler_xgb_2.pkl']

#### LightGBM

In [105]:
X_gbm = all_yields_df_encoded_crops[feature_names]
y_gbm = all_yields_df_encoded_crops["VRYIELDMAS"]

scaler_gbm = StandardScaler()
X_gbm = scaler_gbm.fit_transform(X_gbm)

X_train_gbm, X_test_gbm, y_train_gbm, y_test_gbm = train_test_split(X_gbm, y_gbm, test_size=0.2, random_state=0)

In [106]:
model_gbm = LGBMRegressor(learning_rate=0.1, max_depth=10, n_estimators=100, num_leaves=64)
model_gbm.fit(X_train_gbm, y_train_gbm)

c:\Users\katja\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

LGBMRegressor(max_depth=10, num_leaves=64)

In [107]:
y_pred_gbm = model_gbm.predict(X_test_gbm)

mae_gbm = metrics.mean_absolute_error(y_test_gbm, y_pred_gbm)
mse_gbm = metrics.mean_squared_error(y_test_gbm, y_pred_gbm)
rmse_gbm = np.sqrt(metrics.mean_squared_error(y_test_gbm, y_pred_gbm))
r_2_gbm = r2_score(y_test_gbm, y_pred_gbm)

print('Mean Absolute Error:', mae_gbm)
print('Mean Square Error:', mse_gbm)
print('Root Mean Square Error:', rmse_gbm)
print('R^2:', r_2_gbm)

Mean Absolute Error: 0.6427481573718572
Mean Square Error: 0.9696900488829013
Root Mean Square Error: 0.9847284137684367
R^2: 0.9667112113994115

c:\Users\katja\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

## With weather

In [182]:
all_yields_df_weather = pd.read_csv("./data_1/all_yields_.csv")

In [183]:
all_yields_df_weather.head()

,VRYIELDMAS,SECTIONID,Moisture,Elevation,xcoord,ycoord,area,Organic M,Ca,Mg,...,mean_cloudcover_month_7,mean_cloudcover_month_8,mean_cloudcover_month_9,mean_cloudcover_month_10,std_cloudcover_month_5,std_cloudcover_month_6,std_cloudcover_month_7,std_cloudcover_month_8,std_cloudcover_month_9,std_cloudcover_month_10
0,0.000000,499,14.38,269.856182,25.839963,48.834206,5.18,9.5,4901.0,100.0,...,67.474194,48.309677,59.55,47.425806,24.902733,24.864623,18.293386,24.280985,24.648883,34.1758
1,0.186290,499,14.41,269.818182,25.839974,48.834226,5.18,9.5,4901.0,100.0,...,67.474194,48.309677,59.55,47.425806,24.902733,24.864623,18.293386,24.280985,24.648883,34.1758
2,0.000000,499,14.44,269.751182,25.839979,48.834244,5.18,9.5,4901.0,100.0,...,67.474194,48.309677,59.55,47.425806,24.902733,24.864623,18.293386,24.280985,24.648883,34.1758
3,0.143233,499,14.45,269.748182,25.839986,48.834261,5.18,9.5,4901.0,100.0,...,67.474194,48.309677,59.55,47.425806,24.902733,24.864623,18.293386,24.280985,24.648883,34.1758
4,0.000000,499,14.24,269.713182,25.839996,48.834278,5.18,9.5,4901.0,100.0,...,67.474194,48.309677,59.55,47.425806,24.902733,24.864623,18.293386,24.280985,24.648883,34.1758

### Regressions

In [112]:
all_yields_df_weather.columns

Index(['VRYIELDMAS', 'SECTIONID', 'Moisture', 'Elevation', 'xcoord', 'ycoord',
       'area', 'Organic M', 'Ca', 'Mg',
       ...
       'mean_cloudcover_month_7', 'mean_cloudcover_month_8',
       'mean_cloudcover_month_9', 'mean_cloudcover_month_10',
       'std_cloudcover_month_5', 'std_cloudcover_month_6',
       'std_cloudcover_month_7', 'std_cloudcover_month_8',
       'std_cloudcover_month_9', 'std_cloudcover_month_10'],
      dtype='object', length=172)

In [184]:
feature_names_2 = ["Moisture", "Elevation" , "xcoord" ,
                 "ycoord", "area", "Organic M", "Ca", "Mg", "Mn", "B",
                 "Cu", "Mo", "Fe", "Zn", "S", "P", "K", "Na", "pH", "C.E.C",
                 "year", "Crop_22", "Crop_34", "Crop_41", "Crop_45", "Crop_174", 

    "mean_tempmax_month_5", "mean_tempmax_month_6", "mean_tempmax_month_7",
    "mean_tempmax_month_8", "mean_tempmax_month_9", "mean_tempmax_month_10",
    "std_tempmax_month_5", "std_tempmax_month_6", "std_tempmax_month_7",
    "std_tempmax_month_8", "std_tempmax_month_9", "std_tempmax_month_10",

    "mean_tempmin_month_5", "mean_tempmin_month_6", "mean_tempmin_month_7",
    "mean_tempmin_month_8", "mean_tempmin_month_9", "mean_tempmin_month_10",
    "std_tempmin_month_5", "std_tempmin_month_6", "std_tempmin_month_7",
    "std_tempmin_month_8", "std_tempmin_month_9", "std_tempmin_month_10",

    "mean_temp_month_5", "mean_temp_month_6", "mean_temp_month_7",
    "mean_temp_month_8", "mean_temp_month_9", "mean_temp_month_10",
    "std_temp_month_5", "std_temp_month_6", "std_temp_month_7",
    "std_temp_month_8", "std_temp_month_9", "std_temp_month_10",
    
    "mean_humidity_month_5", "mean_humidity_month_6", "mean_humidity_month_7",
    "mean_humidity_month_8", "mean_humidity_month_9", "mean_humidity_month_10",
    "std_humidity_month_5", "std_humidity_month_6", "std_humidity_month_7",
    "std_humidity_month_8", "std_humidity_month_9", "std_humidity_month_10",
    
    "mean_precip_month_5", "mean_precip_month_6", "mean_precip_month_7",
    "mean_precip_month_8", "mean_precip_month_9", "mean_precip_month_10",
    "std_precip_month_5", "std_precip_month_6", "std_precip_month_7",
    "std_precip_month_8", "std_precip_month_9", "std_precip_month_10",
    
    "mean_cloudcover_month_5", "mean_cloudcover_month_6", "mean_cloudcover_month_7",
    "mean_cloudcover_month_8", "mean_cloudcover_month_9", "mean_cloudcover_month_10",
    "std_cloudcover_month_5", "std_cloudcover_month_6", "std_cloudcover_month_7",
    "std_cloudcover_month_8", "std_cloudcover_month_9", "std_cloudcover_month_10",
    ]

#### MLR

In [185]:
X_mlr_2 = all_yields_df_weather[feature_names_2]
y_mlr_2 = all_yields_df_weather["VRYIELDMAS"]

scaler = StandardScaler()
X_mlr_2 = scaler.fit_transform(X_mlr_2)

X_train_mlr_2, X_test_mlr_2, y_train_mlr_2, y_test_mlr_2 = train_test_split(X_mlr_2, y_mlr_2, test_size=0.2, random_state=0)

In [186]:
reg_model_mlr_2 = LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, positive=False)
reg_model_mlr_2 = LinearRegression().fit(X_train_mlr_2, y_train_mlr_2)

In [187]:
y_pred_mlr_2 = reg_model_mlr_2.predict(X_test_mlr_2)  

mae_mlr_2 = metrics.mean_absolute_error(y_test_mlr_2, y_pred_mlr_2)
mse_mlr_2 = metrics.mean_squared_error(y_test_mlr_2, y_pred_mlr_2)
rmse_mlr_2 = np.sqrt(metrics.mean_squared_error(y_test_mlr_2, y_pred_mlr_2))
r_2_mlr_2 = r2_score(y_test_mlr_2, y_pred_mlr_2)

print('Mean Absolute Error:', mae_mlr_2)
print('Mean Square Error:', mse_mlr_2)
print('Root Mean Square Error:', rmse_mlr_2)
print('R^2:', r_2_mlr_2)

Mean Absolute Error: 0.8611543296025298
Mean Square Error: 1.5505815041621995
Root Mean Square Error: 1.2452234755907068
R^2: 0.9467696095680247

In [188]:
reg_model_mlr_2.get_params()

{'copy_X': True, 'fit_intercept': True, 'n_jobs': None, 'positive': False}

In [189]:
param_grid = {
    'copy_X': [True,False], 
    'fit_intercept': [True,False], 
    'n_jobs': [1, 5, 10, 15, None], 
    'positive': [True,False]
    }

halving_grid_search_mlr = HalvingGridSearchCV(
    reg_model_mlr_2, 
    param_grid, 
    scoring='r2',
    cv=5, 
    n_jobs=-1,
    )
halving_grid_search_mlr.fit(X_train_mlr_2, y_train_mlr_2)

print(f"Best Hyperparameters: {halving_grid_search_mlr.best_params_}")
print(f"Best Score: {halving_grid_search_mlr.best_score_}")

Best Hyperparameters: {'copy_X': True, 'fit_intercept': True, 'n_jobs': 1, 'positive': False}
Best Score: 0.9453135450967194

In [255]:
results_df_mlr = pd.DataFrame(halving_grid_search_mlr.cv_results_)
cols = ['params', 'mean_test_score', 'std_test_score', 'rank_test_score','mean_fit_time']

print(results_df_mlr[cols].sort_values(by='rank_test_score').head().to_markdown(index=False))

| params                                                                      |   mean_test_score |   std_test_score |   rank_test_score |   mean_fit_time |
|:----------------------------------------------------------------------------|------------------:|-----------------:|------------------:|----------------:|
| {'copy_X': False, 'fit_intercept': True, 'n_jobs': None, 'positive': False} |          0.945942 |       0.00133765 |                 1 |        0.640038 |
| {'copy_X': False, 'fit_intercept': True, 'n_jobs': 10, 'positive': False}   |          0.945942 |       0.00133765 |                 1 |        0.732706 |
| {'copy_X': False, 'fit_intercept': True, 'n_jobs': 5, 'positive': False}    |          0.945942 |       0.00133765 |                 1 |        0.698574 |
| {'copy_X': False, 'fit_intercept': True, 'n_jobs': 15, 'positive': False}   |          0.945942 |       0.00133765 |                 1 |        0.668145 |
| {'copy_X': False, 'fit_intercept': True, 'n_jobs': 1, 'positive': False}    |          0.945942 |       0.00133765 |                 1 |        0.686963 |

#### Lasso

In [190]:
X_lasso_2 = all_yields_df_weather[feature_names_2]
y_lasso_2 = all_yields_df_weather["VRYIELDMAS"]

scaler = StandardScaler()
X_lasso_2 = scaler.fit_transform(X_lasso_2)

X_train_lasso_2, X_test_lasso_2, y_train_lasso_2, y_test_lasso_2 = train_test_split(X_lasso_2, y_lasso_2, test_size=0.2, random_state=0)

In [191]:
lasso_model_2 = Lasso(alpha=0.1)
lasso_model_2.fit(X_train_lasso_2, y_train_lasso_2)

Lasso(alpha=0.1)

In [192]:
y_pred_lasso_2 = lasso_model_2.predict(X_test_lasso_2)

mae_lasso_2 = metrics.mean_absolute_error(y_test_lasso_2, y_pred_lasso_2)
mse_lasso_2 = metrics.mean_squared_error(y_test_lasso_2, y_pred_lasso_2)
rmse_lasso_2 = np.sqrt(metrics.mean_squared_error(y_test_lasso_2, y_pred_lasso_2))
r_2_lasso_2 = r2_score(y_test_lasso_2, y_pred_lasso_2)

print('Mean Absolute Error:', mae_lasso_2)
print('Mean Square Error:', mse_lasso_2)
print('Root Mean Square Error:', rmse_lasso_2)
print('R^2:', r_2_lasso_2)

Mean Absolute Error: 0.8833042900454067
Mean Square Error: 1.6166139361554046
Root Mean Square Error: 1.2714613388363032
R^2: 0.9445027618552563

In [193]:
param_grid_lasso = {
    'alpha' : [0.1, 1, 5, 10, 20, 50, 100]
    }

grid_search_lasso = HalvingGridSearchCV(
    lasso_model_2, 
    param_grid_lasso, 
    scoring='r2',
    cv=5, 
    n_jobs=-1,
    )
grid_search_lasso.fit(X_train_lasso_2, y_train_lasso_2)

print(f"Best Hyperparameters: {grid_search_lasso.best_params_}")
print(f"Best Score: {grid_search_lasso.best_score_}")

Best Hyperparameters: {'alpha': 0.1}
Best Score: 0.9428604152107113

In [253]:
results_df_lasso = pd.DataFrame(grid_search_lasso.cv_results_)
cols = ['params', 'mean_test_score', 'std_test_score', 'rank_test_score','mean_fit_time']

print(results_df_lasso[cols].sort_values(by='rank_test_score').head().to_markdown(index=False))

| params         |   mean_test_score |   std_test_score |   rank_test_score |   mean_fit_time |
|:---------------|------------------:|-----------------:|------------------:|----------------:|
| {'alpha': 0.1} |         0.94286   |      0.000738355 |                 1 |       11.1317   |
| {'alpha': 0.1} |         0.941953  |      0.000982162 |                 2 |        3.58956  |
| {'alpha': 1}   |         0.873904  |      0.00100134  |                 3 |        1.61071  |
| {'alpha': 1}   |         0.873399  |      0.00113271  |                 4 |        0.623186 |
| {'alpha': 5}   |        -2.355e-05 |      1.70047e-05 |                 5 |        0.378456 |

#### Ridge

In [194]:
X_ridge_2 = all_yields_df_weather[feature_names_2]
y_ridge_2 = all_yields_df_weather["VRYIELDMAS"]

scaler = StandardScaler()
X_ridge_2 = scaler.fit_transform(X_ridge_2)

X_train_ridge_2, X_test_ridge_2, y_train_ridge_2, y_test_ridge_2 = train_test_split(X_ridge_2, y_ridge_2, test_size=0.2, random_state=0)

In [195]:
ridge_model_2 = Ridge(alpha=0.1)
ridge_model_2.fit(X_train_ridge_2, y_train_ridge_2)

Ridge(alpha=0.1)

In [196]:
y_pred_ridge_2 = ridge_model_2.predict(X_test_ridge_2)
mae_ridge_2 = metrics.mean_absolute_error(y_test_ridge_2, y_pred_ridge_2)
mse_ridge_2 = metrics.mean_squared_error(y_test_ridge_2, y_pred_ridge_2)
rmse_ridge_2 = np.sqrt(metrics.mean_squared_error(y_test_ridge_2, y_pred_ridge_2))
r_2_ridge_2 = r2_score(y_test_ridge_2, y_pred_ridge_2)

print('Mean Absolute Error:', mae_ridge_2)
print('Mean Square Error:', mse_ridge_2)
print('Root Mean Square Error:', rmse_ridge_2)
print('R^2:', r_2_ridge_2)

Mean Absolute Error: 0.8611528517244031
Mean Square Error: 1.550580942247317
Root Mean Square Error: 1.2452232499625586
R^2: 0.946769628858174

In [197]:
param_grid_ridge = {
    'alpha' : [0.0001, 0.001, 0.01, 0.1, 1, 5, 10, 20, 50, 100]
    }

grid_search_ridge = HalvingGridSearchCV(
    ridge_model_2, 
    param_grid_ridge, 
    scoring='r2',
    cv=5, 
    n_jobs=-1,
    )
grid_search_ridge.fit(X_train_ridge_2, y_train_ridge_2)

print(f"Best Hyperparameters: {grid_search_ridge.best_params_}")
print(f"Best Score: {grid_search_ridge.best_score_}")

Best Hyperparameters: {'alpha': 0.001}
Best Score: 0.9453114936818038

In [252]:
results_df_ridge = pd.DataFrame(grid_search_ridge.cv_results_)
cols = ['params', 'mean_test_score', 'std_test_score', 'rank_test_score','mean_fit_time']

print(results_df_ridge[cols].sort_values(by='rank_test_score').head().to_markdown(index=False))

| params            |   mean_test_score |   std_test_score |   rank_test_score |   mean_fit_time |
|:------------------|------------------:|-----------------:|------------------:|----------------:|
| {'alpha': 0.001}  |          0.945311 |      0.000755425 |                 1 |        0.394241 |
| {'alpha': 0.0001} |          0.945311 |      0.000755424 |                 2 |        0.40253  |
| {'alpha': 0.0001} |          0.945112 |      0.00110922  |                 3 |        0.203007 |
| {'alpha': 0.001}  |          0.945112 |      0.00110922  |                 4 |        0.215412 |
| {'alpha': 0.01}   |          0.945112 |      0.00110924  |                 5 |        0.213677 |

#### Polynomial

In [198]:
X_pol_2 = all_yields_df_weather[feature_names_2]
y_pol_2 = all_yields_df_weather["VRYIELDMAS"]

scaler = StandardScaler()
X_pol_2 = scaler.fit_transform(X_pol_2)

X_train_pol_2, X_test_pol_2, y_train_pol_2, y_test_pol_2 = train_test_split(X_pol_2, y_pol_2, test_size=0.2, random_state=0)

In [199]:
lin_pol_2 = LinearRegression()
lin_pol_2.fit(X_train_pol_2, y_train_pol_2)

poly_2 = PolynomialFeatures(degree=2)
X_poly_2 = poly_2.fit_transform(X_train_pol_2)
X_poly_test_2 = poly_2.fit_transform(X_test_pol_2)

poly_2.fit(X_poly_2, y_train_pol_2)
lin2_pol_2 = LinearRegression()
lin2_pol_2.fit(X_poly_2, y_train_pol_2)

LinearRegression()

In [200]:
y_pred_pol_2 = lin2_pol_2.predict(X_poly_test_2)

mae_pol_2 = metrics.mean_absolute_error(y_test_pol_2, y_pred_pol_2)
mse_pol_2 = metrics.mean_squared_error(y_test_pol_2, y_pred_pol_2)
rmse_pol_2 = np.sqrt(metrics.mean_squared_error(y_test_pol_2, y_pred_pol_2))
r_2_pol_2 = r2_score(y_test_pol_2, y_pred_pol_2)

print('Mean Absolute Error:', mae_pol_2)
print('Mean Square Error:', mse_pol_2)
print('Root Mean Square Error:', rmse_pol_2)
print('R^2:', r_2_pol_2)

Mean Absolute Error: 0.7468970148263793
Mean Square Error: 1.2562740205728256
Root Mean Square Error: 1.1208363040929865
R^2: 0.9568729818941245

In [201]:
mae_ = []
mse_ = []
rmse_ = []
r2_ = []

degrees = [1, 2]

for degree in degrees:
    pipeline = Pipeline([('poly_features', PolynomialFeatures(degree=degree)), ('model', LinearRegression())])
    pipeline.fit(X_train_pol_2, y_train_pol_2)

    y_pred_test_ = pipeline.predict(X_test_pol_2)

    mae_.append(metrics.mean_absolute_error(y_test_pol_2, y_pred_pol_2))
    mse_.append(metrics.mean_squared_error(y_test_pol_2, y_pred_pol_2))
    rmse_.append(np.sqrt(metrics.mean_squared_error(y_test_pol_2, y_pred_pol_2)))
    r2_.append(r2_score(y_test_pol_2, y_pred_test_))

In [202]:
print(degrees,'\n')
print("MAE: ", mae_,'\n')
print("MSE: ", mse_, "\n")
print("RMSE: ", rmse_, "\n")
print("R2: ", r2_, "\n")

[1, 2]

MAE:  [0.7468970148263793, 0.7468970148263793]

MSE:  [1.2562740205728256, 1.2562740205728256]

RMSE:  [1.1208363040929865, 1.1208363040929865]

R2:  [0.9467696095680248, 0.9568729818941245]

#### Decision Tree

In [203]:
X_dt_2 = all_yields_df_weather[feature_names_2]
y_dt_2 = all_yields_df_weather["VRYIELDMAS"]

scaler = StandardScaler()
X_dt_2 = scaler.fit_transform(X_dt_2)

X_train_dt_2, X_test_dt_2, y_train_dt_2, y_test_dt_2 = train_test_split(X_dt_2, y_dt_2, test_size=0.2, random_state=0)

In [204]:
regressor_dt_2 = DecisionTreeRegressor(max_depth=10, max_leaf_nodes=64, random_state=42)
regressor_dt_2.fit(X_train_dt_2, y_train_dt_2)

DecisionTreeRegressor(max_depth=10, max_leaf_nodes=64, random_state=42)

In [205]:
y_pred_dt_2 = regressor_dt_2.predict(X_test_dt_2)

mae_dt_2 = metrics.mean_absolute_error(y_test_dt_2, y_pred_dt_2)
mse_dt_2 = metrics.mean_squared_error(y_test_dt_2, y_pred_dt_2)
rmse_dt_2 = np.sqrt(metrics.mean_squared_error(y_test_dt_2, y_pred_dt_2))
r_2_dt_2 = r2_score(y_test_dt_2, y_pred_dt_2)

print('Mean Absolute Error:', mae_dt_2)
print('Mean Square Error:', mse_dt_2)
print('Root Mean Square Error:', rmse_dt_2)
print('R^2:', r_2_dt_2)

Mean Absolute Error: 0.7649338733934814
Mean Square Error: 1.2775105574652235
Root Mean Square Error: 1.1302701258837302
R^2: 0.9561439462728618

In [206]:
param_grid_dt = {
    'max_depth' : [4, 6, 8, 10], 
    'max_leaf_nodes' : [16, 32, 64]
}

halving_grid_search_dt = HalvingGridSearchCV(
    regressor_dt_2, 
    param_grid_dt, 
    scoring='r2',
    cv=5, 
    n_jobs=-1,
)
halving_grid_search_dt.fit(X_train_dt_2, y_train_dt_2)


print(f"Best Hyperparameters: {halving_grid_search_dt.best_params_}")
print(f"Best Score: {halving_grid_search_dt.best_score_}")

Best Hyperparameters: {'max_depth': 10, 'max_leaf_nodes': 64}
Best Score: 0.9552806348604079

In [251]:
results_df_dt = pd.DataFrame(halving_grid_search_dt.cv_results_)
cols = ['params', 'mean_test_score', 'std_test_score', 'rank_test_score','mean_fit_time']

print(results_df_dt[cols].sort_values(by='rank_test_score').head().to_markdown(index=False))

| params                                  |   mean_test_score |   std_test_score |   rank_test_score |   mean_fit_time |
|:----------------------------------------|------------------:|-----------------:|------------------:|----------------:|
| {'max_depth': 10, 'max_leaf_nodes': 64} |          0.955281 |      0.000632832 |                 1 |        2.1707   |
| {'max_depth': 8, 'max_leaf_nodes': 64}  |          0.954931 |      0.00050237  |                 2 |        2.22001  |
| {'max_depth': 10, 'max_leaf_nodes': 64} |          0.954128 |      0.00104902  |                 3 |        0.844445 |
| {'max_depth': 8, 'max_leaf_nodes': 64}  |          0.953842 |      0.00113082  |                 4 |        0.804008 |
| {'max_depth': 6, 'max_leaf_nodes': 64}  |          0.951796 |      0.000697368 |                 5 |        0.810237 |

#### Random Forest

In [207]:
X_rf_2 = all_yields_df_weather[feature_names_2]
y_rf_2 = all_yields_df_weather["VRYIELDMAS"]

scaler = StandardScaler()
X_rf_2 = scaler.fit_transform(X_rf_2)

X_train_rf_2, X_test_rf_2, y_train_rf_2, y_test_rf_2 = train_test_split(X_rf_2, y_rf_2, test_size=0.2, random_state=0)

In [ ]:
regr_rf_2 = RandomForestRegressor(max_depth=10, max_leaf_nodes=64, n_estimators=200)
regr_rf_2.fit(X_train_rf_2, y_train_rf_2)

RandomForestRegressor(max_depth=10, max_leaf_nodes=64, n_estimators=300)

In [209]:
y_pred_rf_2 = regr_rf_2.predict(X_test_rf_2)

mae_rf_2 = metrics.mean_absolute_error(y_test_rf_2, y_pred_rf_2)
mse_rf_2 = metrics.mean_squared_error(y_test_rf_2, y_pred_rf_2)
rmse_rf_2 = np.sqrt(metrics.mean_squared_error(y_test_rf_2, y_pred_rf_2))
r_2_rf_2 = r2_score(y_test_rf_2, y_pred_rf_2)

print('Mean Absolute Error:', mae_rf_2)
print('Mean Square Error:', mse_rf_2)
print('Root Mean Square Error:', rmse_rf_2)
print('R^2:', r_2_rf_2)

Mean Absolute Error: 0.7441814058720924
Mean Square Error: 1.217730924023447
Root Mean Square Error: 1.1035084612378137
R^2: 0.9581961397366975

In [ ]:
param_grid_rf = {
    'max_depth' : [4, 6, 8, 10], 
    'max_leaf_nodes' : [16, 32, 64], 
    'n_estimators' : [50, 100, 200, 300]
}

halving_grid_search_rf = HalvingGridSearchCV(
    regr_rf_2, 
    param_grid_rf, 
    scoring='r2',
    cv=5, 
    n_jobs=-1,
)
halving_grid_search_rf.fit(X_train_rf_2, y_train_rf_2)

print(f"Best Hyperparameters: {halving_grid_search_rf.best_params_}")
print(f"Best Score: {halving_grid_search_rf.best_score_}")

Best Hyperparameters: {'max_depth': 10, 'max_leaf_nodes': 64, 'n_estimators': 200}
Best Score: 0.9575297424151639

In [250]:
results_df_rf = pd.DataFrame(halving_grid_search_rf.cv_results_)
cols = ['params', 'mean_test_score', 'std_test_score', 'rank_test_score','mean_fit_time']

print(results_df_rf[cols].sort_values(by='rank_test_score').head().to_markdown(index=False))

| params                                                       |   mean_test_score |   std_test_score |   rank_test_score |   mean_fit_time |
|:-------------------------------------------------------------|------------------:|-----------------:|------------------:|----------------:|
| {'max_depth': 10, 'max_leaf_nodes': 64, 'n_estimators': 200} |          0.95753  |      0.000545574 |                 1 |        268.495  |
| {'max_depth': 10, 'max_leaf_nodes': 64, 'n_estimators': 300} |          0.957529 |      0.000520462 |                 2 |        374.132  |
| {'max_depth': 10, 'max_leaf_nodes': 64, 'n_estimators': 300} |          0.957414 |      0.00198015  |                 3 |         47.0746 |
| {'max_depth': 10, 'max_leaf_nodes': 64, 'n_estimators': 200} |          0.957398 |      0.00206016  |                 4 |         32.2375 |
| {'max_depth': 10, 'max_leaf_nodes': 64, 'n_estimators': 100} |          0.957307 |      0.00195823  |                 5 |         17.8557 |

#### KNN

In [211]:
X_knn_2 = all_yields_df_weather[feature_names_2]
y_knn_2 = all_yields_df_weather["VRYIELDMAS"]

scaler_knn_2 = StandardScaler()
X_knn_2 = scaler_knn_2.fit_transform(X_knn_2)

X_train_knn_2, X_test_knn_2, y_train_knn_2, y_test_knn_2 = train_test_split(X_knn_2, y_knn_2, test_size=0.2, random_state=0)

In [212]:
knn_reg_2 = KNeighborsRegressor(n_neighbors=3)
knn_reg_2.fit(X_train_knn_2, y_train_knn_2)

KNeighborsRegressor(n_neighbors=3)

In [213]:
os.environ['OMP_NUM_THREADS'] = '1'
y_pred_knn_2 = knn_reg_2.predict(X_test_knn_2)

mae_knn_2 = metrics.mean_absolute_error(y_test_knn_2, y_pred_knn_2)
mse_knn_2 = metrics.mean_squared_error(y_test_knn_2, y_pred_knn_2)
rmse_knn_2 = np.sqrt(metrics.mean_squared_error(y_test_knn_2, y_pred_knn_2))
r_2_knn_2 = r2_score(y_test_knn_2, y_pred_knn_2)

print('Mean Absolute Error:', mae_knn_2)
print('Mean Square Error:', mse_knn_2)
print('Root Mean Square Error:', rmse_knn_2)
print('R^2:', r_2_knn_2)

Mean Absolute Error: 0.3842448045124729
Mean Square Error: 0.5462846890447945
Root Mean Square Error: 0.739110742071034
R^2: 0.9812464245144106

In [15]:
import joblib 

filename = './models/knn.sav'
knn_scaler = "./models/scaler_knn.pkl"
joblib.dump(knn_reg_2, filename)
joblib.dump(scaler_knn_2, knn_scaler)

['./models/scaler_knn.pkl']

In [214]:
param_grid_knn = {
    'n_neighbors' : [2, 3, 5, 10], 
}

halving_grid_search_knn = HalvingGridSearchCV(
    knn_reg_2, 
    param_grid_knn, 
    scoring='r2',
    cv=5, 
    n_jobs=-1,
)
halving_grid_search_knn.fit(X_train_knn_2, y_train_knn_2)


print(f"Best Hyperparameters: {halving_grid_search_knn.best_params_}")
print(f"Best Score: {halving_grid_search_knn.best_score_}")

Best Hyperparameters: {'n_neighbors': 3}
Best Score: 0.9790582417794024

In [249]:
results_df_knn = pd.DataFrame(halving_grid_search_knn.cv_results_)
cols = ['params', 'mean_test_score', 'std_test_score', 'rank_test_score','mean_fit_time']

print(results_df_knn[cols].sort_values(by='rank_test_score').head().to_markdown(index=False))

| params             |   mean_test_score |   std_test_score |   rank_test_score |   mean_fit_time |
|:-------------------|------------------:|-----------------:|------------------:|----------------:|
| {'n_neighbors': 3} |          0.979058 |      0.000190459 |                 1 |        0.165782 |
| {'n_neighbors': 5} |          0.977682 |      0.00027856  |                 2 |        0.165206 |
| {'n_neighbors': 3} |          0.969248 |      0.00133977  |                 3 |        0.126988 |
| {'n_neighbors': 5} |          0.96894  |      0.000886423 |                 4 |        0.116447 |
| {'n_neighbors': 2} |          0.968544 |      0.001708    |                 5 |        0.1343   |

#### Elastcnet

In [215]:
X_en_2 = all_yields_df_weather[feature_names_2]
y_en_2 = all_yields_df_weather["VRYIELDMAS"]

scaler = StandardScaler()
X_en_2 = scaler.fit_transform(X_en_2)

X_train_en_2, X_test_en_2, y_train_en_2, y_test_en_2 = train_test_split(X_en_2, y_en_2, test_size=0.2, random_state=0)

In [216]:
regr_en_2 = ElasticNet(alpha=1, tol=1e-6)
regr_en_2.fit(X_train_en_2, y_train_en_2)

ElasticNet(alpha=1, tol=1e-06)

In [217]:
y_pred_en_2 = regr_en_2.predict(X_test_en_2)

mae_en_2 = metrics.mean_absolute_error(y_test_en_2, y_pred_en_2)
mse_en_2 = metrics.mean_squared_error(y_test_en_2, y_pred_en_2)
rmse_en_2 = np.sqrt(metrics.mean_squared_error(y_test_en_2, y_pred_en_2))
r_2_en_2 = r2_score(y_test_en_2, y_pred_en_2)

print('Mean Absolute Error:', mae_en_2)
print('Mean Square Error:', mse_en_2)
print('Root Mean Square Error:', rmse_en_2)
print('R^2:', r_2_en_2)

Mean Absolute Error: 1.3334504597752512
Mean Square Error: 2.897520172612226
Root Mean Square Error: 1.7022103784821152
R^2: 0.9005301368172781

In [218]:
param_grid_en = {
    'alpha' : [1, 5, 10], 
    'tol' : [1e-4, 1e-6]
}

halving_grid_search_en = HalvingGridSearchCV(
    regr_en_2, 
    param_grid_en, 
    scoring='r2',
    cv=5, 
    n_jobs=-1,
)
halving_grid_search_en.fit(X_train_en_2, y_train_en_2)


print(f"Best Hyperparameters: {halving_grid_search_en.best_params_}")
print(f"Best Score: {halving_grid_search_en.best_score_}")

Best Hyperparameters: {'alpha': 1, 'tol': 1e-06}
Best Score: 0.8988903908271701

In [248]:
results_df_en = pd.DataFrame(halving_grid_search_en.cv_results_)
cols = ['params', 'mean_test_score', 'std_test_score', 'rank_test_score','mean_fit_time']

print(results_df_en[cols].sort_values(by='rank_test_score').head().to_markdown(index=False))

| params                      |   mean_test_score |   std_test_score |   rank_test_score |   mean_fit_time |
|:----------------------------|------------------:|-----------------:|------------------:|----------------:|
| {'alpha': 1, 'tol': 1e-06}  |          0.89889  |       0.00105627 |                 1 |        3.51101  |
| {'alpha': 1, 'tol': 0.0001} |          0.898889 |       0.00105647 |                 2 |        2.04201  |
| {'alpha': 1, 'tol': 1e-06}  |          0.89834  |       0.00105368 |                 3 |        1.29853  |
| {'alpha': 1, 'tol': 0.0001} |          0.898339 |       0.00105299 |                 4 |        1.01585  |
| {'alpha': 5, 'tol': 1e-06}  |          0.46195  |       0.00280132 |                 5 |        0.348584 |

### Gradient boosting

#### XGBoost

In [219]:
X_xgb_2 = all_yields_df_weather[feature_names_2]
y_xgb_2 = all_yields_df_weather["VRYIELDMAS"]

scaler_xgb_2 = StandardScaler()
X_xgb_2 = scaler_xgb_2.fit_transform(X_xgb_2)

X_train_xgb_2, X_test_xgb_2, y_train_xgb_2, y_test_xgb_2 = train_test_split(X_xgb_2, y_xgb_2, test_size=0.2, random_state=0)

In [220]:
regressor_2 = xgb.XGBRegressor(learning_rate = 0.01,
                           n_estimators  = 700,
                           max_depth     = 10,
                           eval_metric   = 'rmse')

regressor_2.fit(X_train_xgb_2, y_train_xgb_2)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric='rmse', feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=0.01, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=10, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=700, n_jobs=None,
             num_parallel_tree=None, random_state=None, ...)

In [221]:
y_pred_xgb_2 = regressor_2.predict(X_test_xgb_2)

mae_xgb_2 = metrics.mean_absolute_error(y_test_xgb_2, y_pred_xgb_2)
mse_xgb_2 = metrics.mean_squared_error(y_test_xgb_2, y_pred_xgb_2)
rmse_xgb_2 = np.sqrt(metrics.mean_squared_error(y_test_xgb_2, y_pred_xgb_2))
r_2_xgb_2 = r2_score(y_test_xgb_2, y_pred_xgb_2)

print('Mean Absolute Error:', mae_xgb_2)
print('Mean Square Error:', mse_xgb_2)
print('Root Mean Square Error:', rmse_xgb_2)
print('R^2:', r_2_xgb_2)

Mean Absolute Error: 0.5436189213850187
Mean Square Error: 0.7323365313982209
Root Mean Square Error: 0.8557666337257026
R^2: 0.9748593934667183

In [10]:
import joblib 

filename = './models/xgb.sav'
scaler_filename = "./models/scaler_xgb.pkl"
joblib.dump(regressor_2, filename)
joblib.dump(scaler_xgb_2, scaler_filename)

['./models/scaler_xgb.pkl']

In [222]:
param_grid_xgb = {
    'max_depth': [2, 4, 6, 8, 10],
    'learning_rate': [0.1, 0.01, 0.001],
    'n_estimators' : [300, 500, 700], 
    'eval_metric' : ['rmse']
    }

grid_search_xgb = HalvingGridSearchCV(
    regressor_2, 
    param_grid_xgb, 
    scoring='r2',
    cv=5, 
    n_jobs=-1,
)

grid_search_xgb.fit(X_train_xgb_2, y_train_xgb_2)

print("Best set of hyperparameters: ", grid_search_xgb.best_params_)
print("Best score: ", grid_search_xgb.best_score_)

Best set of hyperparameters:  {'eval_metric': 'rmse', 'learning_rate': 0.1, 'max_depth': 10, 'n_estimators': 300}
Best score:  0.9787378425322568

In [247]:
results_df_xgb = pd.DataFrame(grid_search_xgb.cv_results_)
cols = ['params', 'mean_test_score', 'std_test_score', 'rank_test_score','mean_fit_time']

print(results_df_xgb[cols].sort_values(by='rank_test_score').head().to_markdown(index=False))

| params                                                                               |   mean_test_score |   std_test_score |   rank_test_score |   mean_fit_time |
|:-------------------------------------------------------------------------------------|------------------:|-----------------:|------------------:|----------------:|
| {'eval_metric': 'rmse', 'learning_rate': 0.1, 'max_depth': 10, 'n_estimators': 300}  |          0.978738 |      0.000430862 |                 1 |         26.3194 |
| {'eval_metric': 'rmse', 'learning_rate': 0.1, 'max_depth': 8, 'n_estimators': 300}   |          0.975001 |      0.000481171 |                 2 |         19.9582 |
| {'eval_metric': 'rmse', 'learning_rate': 0.1, 'max_depth': 10, 'n_estimators': 300}  |          0.972268 |      0.000973249 |                 3 |         21.0037 |
| {'eval_metric': 'rmse', 'learning_rate': 0.1, 'max_depth': 8, 'n_estimators': 300}   |          0.970937 |      0.000966689 |                 4 |         14.5501 |
| {'eval_metric': 'rmse', 'learning_rate': 0.01, 'max_depth': 10, 'n_estimators': 700} |          0.970337 |      0.00111857  |                 5 |         46.3475 |

#### LightGBM

In [223]:
X_gbm_2 = all_yields_df_weather[feature_names_2]
y_gbm_2 = all_yields_df_weather["VRYIELDMAS"]

scaler = StandardScaler()
X_gbm_2 = scaler.fit_transform(X_gbm_2)

X_train_gbm_2, X_test_gbm_2, y_train_gbm_2, y_test_gbm_2 = train_test_split(X_gbm_2, y_gbm_2, test_size=0.2, random_state=0)

In [224]:
model_gbm_2 = LGBMRegressor(learning_rate=0.1, max_depth=10, n_estimators=100, num_leaves=64)
model_gbm_2.fit(X_train_gbm_2, y_train_gbm_2)

c:\Users\katja\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

LGBMRegressor(max_depth=10, num_leaves=64)

In [225]:
y_pred_gbm_2 = model_gbm_2.predict(X_test_gbm_2)

mae_gbm_2 = metrics.mean_absolute_error(y_test_gbm_2, y_pred_gbm_2)
mse_gbm_2 = metrics.mean_squared_error(y_test_gbm_2, y_pred_gbm_2)
rmse_gbm_2 = np.sqrt(metrics.mean_squared_error(y_test_gbm_2, y_pred_gbm_2))
r_2_gbm_2 = r2_score(y_test_gbm_2, y_pred_gbm_2)

print('Mean Absolute Error:', mae_gbm_2)
print('Mean Square Error:', mse_gbm_2)
print('Root Mean Square Error:', rmse_gbm_2)
print('R^2:', r_2_gbm_2)

Mean Absolute Error: 0.6275568219144967
Mean Square Error: 0.9158568078346337
Root Mean Square Error: 0.9570040793197455
R^2: 0.968559269325761

c:\Users\katja\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

In [226]:
param_grid_gbm = {
    'num_leaves' : [16, 31, 32, 64], 
    'max_depth' : [2, 4, 6, 8, 10], 
    'learning_rate' : [0.01, 0.1], 
    'n_estimators' : [50, 100, 300], 
}

halving_grid_search_gbm = HalvingGridSearchCV(
    model_gbm_2, 
    param_grid_gbm, 
    scoring='r2',
    cv=5, 
    n_jobs=-1,
)
halving_grid_search_gbm.fit(X_train_gbm_2, y_train_gbm_2)


print(f"Best Hyperparameters: {halving_grid_search_gbm.best_params_}")
print(f"Best Score: {halving_grid_search_gbm.best_score_}")

c:\Users\katja\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

Best Hyperparameters: {'learning_rate': 0.1, 'max_depth': 10, 'n_estimators': 50, 'num_leaves': 64}
Best Score: 0.9647846970778705

In [ ]:
results_df_gbm = pd.DataFrame(halving_grid_search_gbm.cv_results_)
cols = ['params', 'mean_test_score', 'std_test_score', 'rank_test_score','mean_fit_time']

print(results_df_gbm[cols].sort_values(by='rank_test_score').head().to_markdown(index=False))

| params                                                                         |   mean_test_score |   std_test_score |   rank_test_score |   mean_fit_time |
|:-------------------------------------------------------------------------------|------------------:|-----------------:|------------------:|----------------:|
| {'learning_rate': 0.1, 'max_depth': 10, 'n_estimators': 50, 'num_leaves': 64}  |          0.964785 |      0.000503797 |                 1 |         8.40945 |
| {'learning_rate': 0.1, 'max_depth': 10, 'n_estimators': 100, 'num_leaves': 32} |          0.964488 |      0.000555359 |                 2 |        10.9247  |
| {'learning_rate': 0.1, 'max_depth': 10, 'n_estimators': 50, 'num_leaves': 64}  |          0.96414  |      0.000718009 |                 3 |         4.39521 |
| {'learning_rate': 0.1, 'max_depth': 10, 'n_estimators': 100, 'num_leaves': 32} |          0.963925 |      0.000723642 |                 4 |         5.30064 |
| {'learning_rate': 0.1, 'max_depth': 8, 'n_estimators': 100, 'num_leaves': 32}  |          0.963828 |      0.000853965 |                 5 |         4.91918 |

## Without technical features

In [91]:
feature_names_5 = ["Organic M", "Ca", "Mg", "Mn", "B",
                 "Cu", "Mo", "Fe", "Zn", "S", "P", "K", "Na", "pH", "C.E.C",
                 "Crop_22", "Crop_34", "Crop_41", "Crop_45", "Crop_174", 

    "mean_tempmax_month_5", "mean_tempmax_month_6", "mean_tempmax_month_7",
    "mean_tempmax_month_8", "mean_tempmax_month_9", "mean_tempmax_month_10",
    "std_tempmax_month_5", "std_tempmax_month_6", "std_tempmax_month_7",
    "std_tempmax_month_8", "std_tempmax_month_9", "std_tempmax_month_10",

    "mean_tempmin_month_5", "mean_tempmin_month_6", "mean_tempmin_month_7",
    "mean_tempmin_month_8", "mean_tempmin_month_9", "mean_tempmin_month_10",
    "std_tempmin_month_5", "std_tempmin_month_6", "std_tempmin_month_7",
    "std_tempmin_month_8", "std_tempmin_month_9", "std_tempmin_month_10",

    "mean_temp_month_5", "mean_temp_month_6", "mean_temp_month_7",
    "mean_temp_month_8", "mean_temp_month_9", "mean_temp_month_10",
    "std_temp_month_5", "std_temp_month_6", "std_temp_month_7",
    "std_temp_month_8", "std_temp_month_9", "std_temp_month_10",
    
    "mean_humidity_month_5", "mean_humidity_month_6", "mean_humidity_month_7",
    "mean_humidity_month_8", "mean_humidity_month_9", "mean_humidity_month_10",
    "std_humidity_month_5", "std_humidity_month_6", "std_humidity_month_7",
    "std_humidity_month_8", "std_humidity_month_9", "std_humidity_month_10",
    
    "mean_precip_month_5", "mean_precip_month_6", "mean_precip_month_7",
    "mean_precip_month_8", "mean_precip_month_9", "mean_precip_month_10",
    "std_precip_month_5", "std_precip_month_6", "std_precip_month_7",
    "std_precip_month_8", "std_precip_month_9", "std_precip_month_10",
    
    "mean_cloudcover_month_5", "mean_cloudcover_month_6", "mean_cloudcover_month_7",
    "mean_cloudcover_month_8", "mean_cloudcover_month_9", "mean_cloudcover_month_10",
    "std_cloudcover_month_5", "std_cloudcover_month_6", "std_cloudcover_month_7",
    "std_cloudcover_month_8", "std_cloudcover_month_9", "std_cloudcover_month_10",
    ]

In [92]:
X_xgb_5 = all_yields_df_weather[feature_names_5]
y_xgb_5 = all_yields_df_weather["VRYIELDMAS"]

scaler_xgb_5 = StandardScaler()
X_xgb_5 = scaler_xgb_5.fit_transform(X_xgb_5)

X_train_xgb_5, X_test_xgb_5, y_train_xgb_5, y_test_xgb_5 = train_test_split(X_xgb_5, y_xgb_5, test_size=0.2, random_state=0)

In [93]:
regressor_5 = xgb.XGBRegressor(learning_rate = 0.01,
                           n_estimators  = 700,
                           max_depth     = 10,
                           eval_metric   = 'rmse')

regressor_5.fit(X_train_xgb_5, y_train_xgb_5)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric='rmse', feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=0.01, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=10, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=700, n_jobs=None,
             num_parallel_tree=None, random_state=None, ...)

In [ ]:
import joblib 

filename = './models/xgb_.sav'
scaler_filename = "./models/scaler_xgb_.pkl"
joblib.dump(regressor_5, filename)
joblib.dump(scaler_xgb_5, scaler_filename)

['./models/scaler_xgb_.pkl']

In [94]:
y_pred_xgb_5 = regressor_5.predict(X_test_xgb_5)

mae_xgb_5 = metrics.mean_absolute_error(y_test_xgb_5, y_pred_xgb_5)
mse_xgb_5 = metrics.mean_squared_error(y_test_xgb_5, y_pred_xgb_5)
rmse_xgb_5 = np.sqrt(metrics.mean_squared_error(y_test_xgb_5, y_pred_xgb_5))
r_2_xgb_5 = r2_score(y_test_xgb_5, y_pred_xgb_5)

print('Mean Absolute Error:', mae_xgb_5)
print('Mean Square Error:', mse_xgb_5)
print('Root Mean Square Error:', rmse_xgb_5)
print('R^2:', r_2_xgb_5)

Mean Absolute Error: 0.8217688910754996
Mean Square Error: 1.4615090315635897
Root Mean Square Error: 1.2089288777937226
R^2: 0.94982740593696

In [95]:
X_knn_5 = all_yields_df_weather[feature_names_5]
y_knn_5 = all_yields_df_weather["VRYIELDMAS"]

scaler_knn_5 = StandardScaler()
X_knn_5 = scaler_knn_5.fit_transform(X_knn_5)

X_train_knn_5, X_test_knn_5, y_train_knn_5, y_test_knn_5 = train_test_split(X_knn_5, y_knn_5, test_size=0.2, random_state=0)

In [97]:
knn_reg_5 = KNeighborsRegressor(n_neighbors=3)
knn_reg_5.fit(X_train_knn_5, y_train_knn_5)

KNeighborsRegressor(n_neighbors=3)

In [98]:
os.environ['OMP_NUM_THREADS'] = '1'
y_pred_knn_5 = knn_reg_5.predict(X_test_knn_5)

mae_knn_5 = metrics.mean_absolute_error(y_test_knn_5, y_pred_knn_5)
mse_knn_5 = metrics.mean_squared_error(y_test_knn_5, y_pred_knn_5)
rmse_knn_5 = np.sqrt(metrics.mean_squared_error(y_test_knn_5, y_pred_knn_5))
r_2_knn_5 = r2_score(y_test_knn_5, y_pred_knn_5)

print('Mean Absolute Error:', mae_knn_5)
print('Mean Square Error:', mse_knn_5)
print('Root Mean Square Error:', rmse_knn_5)
print('R^2:', r_2_knn_5)

Mean Absolute Error: 0.9050483909241005
Mean Square Error: 1.7179985105820395
Root Mean Square Error: 1.3107244220590533
R^2: 0.9410222995473911

## Without year and coordinates

In [151]:
feature_names_6 = ["Elevation", "area", "Organic M", "Ca", "Mg", "Mn", "B",
                 "Cu", "Mo", "Fe", "Zn", "S", "P", "K", "Na", "pH", "C.E.C",
                 "Crop_22", "Crop_34", "Crop_41", "Crop_45", "Crop_174", 

    "mean_tempmax_month_5", "mean_tempmax_month_6", "mean_tempmax_month_7",
    "mean_tempmax_month_8", "mean_tempmax_month_9", "mean_tempmax_month_10",
    "std_tempmax_month_5", "std_tempmax_month_6", "std_tempmax_month_7",
    "std_tempmax_month_8", "std_tempmax_month_9", "std_tempmax_month_10",

    "mean_tempmin_month_5", "mean_tempmin_month_6", "mean_tempmin_month_7",
    "mean_tempmin_month_8", "mean_tempmin_month_9", "mean_tempmin_month_10",
    "std_tempmin_month_5", "std_tempmin_month_6", "std_tempmin_month_7",
    "std_tempmin_month_8", "std_tempmin_month_9", "std_tempmin_month_10",

    "mean_temp_month_5", "mean_temp_month_6", "mean_temp_month_7",
    "mean_temp_month_8", "mean_temp_month_9", "mean_temp_month_10",
    "std_temp_month_5", "std_temp_month_6", "std_temp_month_7",
    "std_temp_month_8", "std_temp_month_9", "std_temp_month_10",
    
    "mean_humidity_month_5", "mean_humidity_month_6", "mean_humidity_month_7",
    "mean_humidity_month_8", "mean_humidity_month_9", "mean_humidity_month_10",
    "std_humidity_month_5", "std_humidity_month_6", "std_humidity_month_7",
    "std_humidity_month_8", "std_humidity_month_9", "std_humidity_month_10",
    
    "mean_precip_month_5", "mean_precip_month_6", "mean_precip_month_7",
    "mean_precip_month_8", "mean_precip_month_9", "mean_precip_month_10",
    "std_precip_month_5", "std_precip_month_6", "std_precip_month_7",
    "std_precip_month_8", "std_precip_month_9", "std_precip_month_10",
    
    "mean_cloudcover_month_5", "mean_cloudcover_month_6", "mean_cloudcover_month_7",
    "mean_cloudcover_month_8", "mean_cloudcover_month_9", "mean_cloudcover_month_10",
    "std_cloudcover_month_5", "std_cloudcover_month_6", "std_cloudcover_month_7",
    "std_cloudcover_month_8", "std_cloudcover_month_9", "std_cloudcover_month_10",
    ]

### Regressions

#### MLR

In [152]:
X_mlr_6 = all_yields_df_weather[feature_names_6]
y_mlr_6 = all_yields_df_weather["VRYIELDMAS"]

scaler_mlr_6 = StandardScaler()
X_mlr_6 = scaler.fit_transform(X_mlr_6)

X_train_mlr_6, X_test_mlr_6, y_train_mlr_6, y_test_mlr_6 = train_test_split(X_mlr_6, y_mlr_6, test_size=0.2, random_state=0)

In [153]:
reg_model_mlr_6 = LinearRegression(copy_X=True, fit_intercept=True, n_jobs=15, positive=False)
reg_model_mlr_6 = LinearRegression().fit(X_train_mlr_6, y_train_mlr_6)

In [154]:
y_pred_mlr_6 = reg_model_mlr_6.predict(X_test_mlr_6)  

mae_mlr_6 = metrics.mean_absolute_error(y_test_mlr_6, y_pred_mlr_6)
mse_mlr_6 = metrics.mean_squared_error(y_test_mlr_6, y_pred_mlr_6)
rmse_mlr_6 = np.sqrt(metrics.mean_squared_error(y_test_mlr_6, y_pred_mlr_6))
r_2_mlr_6 = r2_score(y_test_mlr_6, y_pred_mlr_6)

print('Mean Absolute Error:', mae_mlr_6)
print('Mean Square Error:', mse_mlr_6)
print('Root Mean Square Error:', rmse_mlr_6)
print('R^2:', r_2_mlr_6)

Mean Absolute Error: 0.8785673803090305
Mean Square Error: 1.591008165045739
Root Mean Square Error: 1.2613517213869172
R^2: 0.945381790264805

In [28]:
param_grid = {
    'copy_X': [True,False], 
    'fit_intercept': [True,False], 
    'n_jobs': [1, 5, 10, 15, None], 
    'positive': [True,False]
    }

halving_grid_search_mlr_6 = HalvingGridSearchCV(
    reg_model_mlr_6, 
    param_grid, 
    scoring='r2',
    cv=5, 
    n_jobs=-1,
    )
halving_grid_search_mlr_6.fit(X_train_mlr_6, y_train_mlr_6)

print(f"Best Hyperparameters: {halving_grid_search_mlr_6.best_params_}")
print(f"Best Score: {halving_grid_search_mlr_6.best_score_}")

Best Hyperparameters: {'copy_X': True, 'fit_intercept': True, 'n_jobs': 1, 'positive': False}
Best Score: 0.9453110620216363

#### Lasso

In [155]:
X_lasso_6 = all_yields_df_weather[feature_names_6]
y_lasso_6 = all_yields_df_weather["VRYIELDMAS"]

scaler_lasso_6 = StandardScaler()
X_lasso_6 = scaler_lasso_6.fit_transform(X_lasso_6)

X_train_lasso_6, X_test_lasso_6, y_train_lasso_6, y_test_lasso_6 = train_test_split(X_lasso_6, y_lasso_6, test_size=0.2, random_state=0)

In [156]:
lasso_model_6 = Lasso(alpha=0.1)
lasso_model_6.fit(X_train_lasso_6, y_train_lasso_6)

Lasso(alpha=0.1)

In [157]:
y_pred_lasso_6 = lasso_model_6.predict(X_test_lasso_6)

mae_lasso_6 = metrics.mean_absolute_error(y_test_lasso_6, y_pred_lasso_6)
mse_lasso_6 = metrics.mean_squared_error(y_test_lasso_6, y_pred_lasso_6)
rmse_lasso_6 = np.sqrt(metrics.mean_squared_error(y_test_lasso_6, y_pred_lasso_6))
r_2_lasso_6 = r2_score(y_test_lasso_6, y_pred_lasso_6)

print('Mean Absolute Error:', mae_lasso_6)
print('Mean Square Error:', mse_lasso_6)
print('Root Mean Square Error:', rmse_lasso_6)
print('R^2:', r_2_lasso_6)

Mean Absolute Error: 0.9158942574131629
Mean Square Error: 1.6930181012071475
Root Mean Square Error: 1.3011602903590116
R^2: 0.9418798597211754

In [34]:
param_grid_lasso = {
    'alpha' : [0.1, 1, 5, 10, 20, 50, 100]
    }

grid_search_lasso = HalvingGridSearchCV(
    lasso_model_6, 
    param_grid_lasso, 
    scoring='r2',
    cv=5, 
    n_jobs=-1,
    )
grid_search_lasso.fit(X_train_lasso_6, y_train_lasso_6)

print(f"Best Hyperparameters: {grid_search_lasso.best_params_}")
print(f"Best Score: {grid_search_lasso.best_score_}")

Best Hyperparameters: {'alpha': 0.1}
Best Score: 0.9428581984824141

#### Ridge

In [158]:
X_ridge_6 = all_yields_df_weather[feature_names_6]
y_ridge_6 = all_yields_df_weather["VRYIELDMAS"]

scaler_ridge_6 = StandardScaler()
X_ridge_6 = scaler_ridge_6.fit_transform(X_ridge_6)

X_train_ridge_6, X_test_ridge_6, y_train_ridge_6, y_test_ridge_6 = train_test_split(X_ridge_6, y_ridge_6, test_size=0.2, random_state=0)

In [159]:
ridge_model_6 = Ridge(alpha=5)
ridge_model_6.fit(X_train_ridge_6, y_train_ridge_6)

Ridge(alpha=5)

In [160]:
y_pred_ridge_6 = ridge_model_6.predict(X_test_ridge_6)

mae_ridge_6 = metrics.mean_absolute_error(y_test_ridge_6, y_pred_ridge_6)
mse_ridge_6 = metrics.mean_squared_error(y_test_ridge_6, y_pred_ridge_6)
rmse_ridge_6 = np.sqrt(metrics.mean_squared_error(y_test_ridge_6, y_pred_ridge_6))
r_2_ridge_6 = r2_score(y_test_ridge_6, y_pred_ridge_6)

print('Mean Absolute Error:', mae_ridge_6)
print('Mean Square Error:', mse_ridge_6)
print('Root Mean Square Error:', rmse_ridge_6)
print('R^2:', r_2_ridge_6)

Mean Absolute Error: 0.8783878463474143
Mean Square Error: 1.5909679348156256
Root Mean Square Error: 1.2613357740172224
R^2: 0.9453831713407757

#### Polynomial

In [161]:
X_pol_6 = all_yields_df_weather[feature_names_6]
y_pol_6 = all_yields_df_weather["VRYIELDMAS"]

scaler_pol_6 = StandardScaler()
X_pol_6 = scaler_pol_6.fit_transform(X_pol_6)

X_train_pol_6, X_test_pol_6, y_train_pol_6, y_test_pol_6 = train_test_split(X_pol_6, y_pol_6, test_size=0.2, random_state=0)

In [162]:
lin_pol_6 = LinearRegression()
lin_pol_6.fit(X_train_pol_6, y_train_pol_6)

poly_6 = PolynomialFeatures(degree=2)
X_poly_6 = poly_6.fit_transform(X_train_pol_6)
X_poly_test_6 = poly_6.fit_transform(X_test_pol_6)

poly_6.fit(X_poly_6, y_train_pol_6)
lin2_pol_6 = LinearRegression()
lin2_pol_6.fit(X_poly_6, y_train_pol_6)

LinearRegression()

In [163]:
y_pred_pol_6 = lin2_pol_6.predict(X_poly_test_6)

mae_pol_6 = metrics.mean_absolute_error(y_test_pol_6, y_pred_pol_6)
mse_pol_6 = metrics.mean_squared_error(y_test_pol_6, y_pred_pol_6)
rmse_pol_6 = np.sqrt(metrics.mean_squared_error(y_test_pol_6, y_pred_pol_6))
r_2_pol_6 = r2_score(y_test_pol_6, y_pred_pol_6)

print('Mean Absolute Error:', mae_pol_6)
print('Mean Square Error:', mse_pol_6)
print('Root Mean Square Error:', rmse_pol_6)
print('R^2:', r_2_pol_6)

Mean Absolute Error: 0.7961456312334717
Mean Square Error: 1.3930085625212
Root Mean Square Error: 1.180257837305561
R^2: 0.9521789796543765

#### Decision tree

In [164]:
X_dt_6 = all_yields_df_weather[feature_names_6]
y_dt_6 = all_yields_df_weather["VRYIELDMAS"]

scaler_dt_6 = StandardScaler()
X_dt_6 = scaler_dt_6.fit_transform(X_dt_6)

X_train_dt_6, X_test_dt_6, y_train_dt_6, y_test_dt_6 = train_test_split(X_dt_6, y_dt_6, test_size=0.2, random_state=0)

In [165]:
regressor_dt_6 = DecisionTreeRegressor(max_depth=6, max_leaf_nodes=64, random_state=42)
regressor_dt_6.fit(X_train_dt_6, y_train_dt_6)

DecisionTreeRegressor(max_depth=6, max_leaf_nodes=64, random_state=42)

In [166]:
y_pred_dt_6 = regressor_dt_6.predict(X_test_dt_6)

mae_dt_6 = metrics.mean_absolute_error(y_test_dt_6, y_pred_dt_6)
mse_dt_6 = metrics.mean_squared_error(y_test_dt_6, y_pred_dt_6)
rmse_dt_6 = np.sqrt(metrics.mean_squared_error(y_test_dt_6, y_pred_dt_6))
r_2_dt_6 = r2_score(y_test_dt_6, y_pred_dt_6)

print('Mean Absolute Error:', mae_dt_6)
print('Mean Square Error:', mse_dt_6)
print('Root Mean Square Error:', rmse_dt_6)
print('R^2:', r_2_dt_6)

Mean Absolute Error: 0.7961067820366636
Mean Square Error: 1.3979081206794328
Root Mean Square Error: 1.1823316458081603
R^2: 0.9520107812120457

#### Random Forest

In [167]:
X_rf_6 = all_yields_df_weather[feature_names_6]
y_rf_6 = all_yields_df_weather["VRYIELDMAS"]

scaler_rf_6 = StandardScaler()
X_rf_6 = scaler_rf_6.fit_transform(X_rf_6)

X_train_rf_6, X_test_rf_6, y_train_rf_6, y_test_rf_6 = train_test_split(X_rf_6, y_rf_6, test_size=0.2, random_state=0)

In [168]:
regr_rf_6 = RandomForestRegressor(max_depth=10, max_leaf_nodes=32, n_estimators=100)
regr_rf_6.fit(X_train_rf_6, y_train_rf_6)

RandomForestRegressor(max_depth=10, max_leaf_nodes=32)

In [169]:
y_pred_rf_6 = regr_rf_6.predict(X_test_rf_6)

mae_rf_6 = metrics.mean_absolute_error(y_test_rf_6, y_pred_rf_6)
mse_rf_6 = metrics.mean_squared_error(y_test_rf_6, y_pred_rf_6)
rmse_rf_6 = np.sqrt(metrics.mean_squared_error(y_test_rf_6, y_pred_rf_6))
r_2_rf_6 = r2_score(y_test_rf_6, y_pred_rf_6)

print('Mean Absolute Error:', mae_rf_6)
print('Mean Square Error:', mse_rf_6)
print('Root Mean Square Error:', rmse_rf_6)
print('R^2:', r_2_rf_6)

Mean Absolute Error: 0.8030606713788938
Mean Square Error: 1.4000134386528609
Root Mean Square Error: 1.183221635473617
R^2: 0.9519385071023596

#### KNN

In [170]:
X_knn_6 = all_yields_df_weather[feature_names_6]
y_knn_6 = all_yields_df_weather["VRYIELDMAS"]

scaler_knn_6 = StandardScaler()
X_knn_6 = scaler_knn_6.fit_transform(X_knn_6)

X_train_knn_6, X_test_knn_6, y_train_knn_6, y_test_knn_6 = train_test_split(X_knn_6, y_knn_6, test_size=0.2, random_state=0)

In [171]:
knn_reg_6 = KNeighborsRegressor(n_neighbors=3)
knn_reg_6.fit(X_train_knn_6, y_train_knn_6)

KNeighborsRegressor(n_neighbors=3)

In [172]:
os.environ['OMP_NUM_THREADS'] = '1'
y_pred_knn_6 = knn_reg_6.predict(X_test_knn_6)

mae_knn_6 = metrics.mean_absolute_error(y_test_knn_6, y_pred_knn_6)
mse_knn_6 = metrics.mean_squared_error(y_test_knn_6, y_pred_knn_6)
rmse_knn_6 = np.sqrt(metrics.mean_squared_error(y_test_knn_6, y_pred_knn_6))
r_2_knn_6 = r2_score(y_test_knn_6, y_pred_knn_6)

print('Mean Absolute Error:', mae_knn_6)
print('Mean Square Error:', mse_knn_6)
print('Root Mean Square Error:', rmse_knn_6)
print('R^2:', r_2_knn_6)

Mean Absolute Error: 0.8493991970554821
Mean Square Error: 1.6301116111894107
Root Mean Square Error: 1.2767582430473714
R^2: 0.9440393960082786

#### Elastic Net

In [173]:
X_en_6 = all_yields_df_weather[feature_names_6]
y_en_6 = all_yields_df_weather["VRYIELDMAS"]

scaler_en_6 = StandardScaler()
X_en_6 = scaler_en_6.fit_transform(X_en_6)

X_train_en_6, X_test_en_6, y_train_en_6, y_test_en_6 = train_test_split(X_en_6, y_en_6, test_size=0.2, random_state=0)

In [174]:
regr_en_6 = ElasticNet(alpha=1, tol=1e-4)
regr_en_6.fit(X_train_en_6, y_train_en_6)

ElasticNet(alpha=1)

In [175]:
y_pred_en_6 = regr_en_6.predict(X_test_en_6)

mae_en_6 = metrics.mean_absolute_error(y_test_en_6, y_pred_en_6)
mse_en_6 = metrics.mean_squared_error(y_test_en_6, y_pred_en_6)
rmse_en_6 = np.sqrt(metrics.mean_squared_error(y_test_en_6, y_pred_en_6))
r_2_en_6 = r2_score(y_test_en_6, y_pred_en_6)

print('Mean Absolute Error:', mae_en_6)
print('Mean Square Error:', mse_en_6)
print('Root Mean Square Error:', rmse_en_6)
print('R^2:', r_2_en_6)

Mean Absolute Error: 1.3435914380702951
Mean Square Error: 2.9285129517957484
Root Mean Square Error: 1.7112898503163478
R^2: 0.899466176146986

### Gradient Boosting

#### LightGBM

In [176]:
X_gbm_6 = all_yields_df_weather[feature_names_6]
y_gbm_6 = all_yields_df_weather["VRYIELDMAS"]

scaler_gbm_6 = StandardScaler()
X_gbm_6 = scaler_gbm_6.fit_transform(X_gbm_6)

X_train_gbm_6, X_test_gbm_6, y_train_gbm_6, y_test_gbm_6 = train_test_split(X_gbm_6, y_gbm_6, test_size=0.2, random_state=0)

In [177]:
model_gbm_6 = LGBMRegressor(learning_rate=0.1, max_depth=10, n_estimators=300, num_leaves=31)
model_gbm_6.fit(X_train_gbm_6, y_train_gbm_6)

c:\Users\katja\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

LGBMRegressor(max_depth=10, n_estimators=300)

In [178]:
y_pred_gbm_6 = model_gbm_6.predict(X_test_gbm_6)

mae_gbm_6 = metrics.mean_absolute_error(y_test_gbm_6, y_pred_gbm_6)
mse_gbm_6 = metrics.mean_squared_error(y_test_gbm_6, y_pred_gbm_6)
rmse_gbm_6 = np.sqrt(metrics.mean_squared_error(y_test_gbm_6, y_pred_gbm_6))
r_2_gbm_6 = r2_score(y_test_gbm_6, y_pred_gbm_6)

print('Mean Absolute Error:', mae_gbm_6)
print('Mean Square Error:', mse_gbm_6)
print('Root Mean Square Error:', rmse_gbm_6)
print('R^2:', r_2_gbm_6)

Mean Absolute Error: 0.7446322110224988
Mean Square Error: 1.256453418106062
Root Mean Square Error: 1.1209163296633973
R^2: 0.9568668233009057

c:\Users\katja\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

#### XGBoost

In [179]:
X_xgb_6 = all_yields_df_weather[feature_names_6]
y_xgb_6 = all_yields_df_weather["VRYIELDMAS"]

scaler_xgb_6 = StandardScaler()
X_xgb_6 = scaler_xgb_6.fit_transform(X_xgb_6)

X_train_xgb_6, X_test_xgb_6, y_train_xgb_6, y_test_xgb_6 = train_test_split(X_xgb_6, y_xgb_6, test_size=0.2, random_state=0)

In [180]:
regressor_6 = xgb.XGBRegressor(learning_rate = 0.01,
                           n_estimators  = 500,
                           max_depth     = 8,
                           eval_metric   = 'rmse')

regressor_6.fit(X_train_xgb_6, y_train_xgb_6)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric='rmse', feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=0.01, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=8, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=500, n_jobs=None,
             num_parallel_tree=None, random_state=None, ...)

In [181]:
y_pred_xgb_6 = regressor_6.predict(X_test_xgb_6)

mae_xgb_6 = metrics.mean_absolute_error(y_test_xgb_6, y_pred_xgb_6)
mse_xgb_6 = metrics.mean_squared_error(y_test_xgb_6, y_pred_xgb_6)
rmse_xgb_6 = np.sqrt(metrics.mean_squared_error(y_test_xgb_6, y_pred_xgb_6))
r_2_xgb_6 = r2_score(y_test_xgb_6, y_pred_xgb_6)

print('Mean Absolute Error:', mae_xgb_6)
print('Mean Square Error:', mse_xgb_6)
print('Root Mean Square Error:', rmse_xgb_6)
print('R^2:', r_2_xgb_6)

Mean Absolute Error: 0.7451031326601357
Mean Square Error: 1.2615648820300844
Root Mean Square Error: 1.1231940535945177
R^2: 0.95669135028022